<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\R3.Application\R3.Application.csproj" />
    <ProjectReference Include="..\R3.Infrastructure\R3.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Krypton.Navigator" Version="105.26.7.201" />
    <PackageReference Include="Krypton.Ribbon" Version="105.26.7.201" />
    <PackageReference Include="Krypton.Toolkit" Version="105.26.7.201" />
    <PackageReference Include="Krypton.Workspace" Version="105.26.7.201" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>R3</AssemblyName>
    <RootNamespace>R3.Desktop</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Branding\R3.ico</ApplicationIcon>
    <Product>R3 ERP</Product>
    <AssemblyTitle>R3 Kurumsal Kaynak Planlama Sistemi</AssemblyTitle>
    <Company>R3</Company>
    <Description>R3 Kurumsal Kaynak Planlama Sistemi</Description>
    <Copyright>Copyright © R3 2026</Copyright>
    <Version>1.0.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);CA1859;CA1861</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Branding\R3.ico" />
    <EmbeddedResource Include="Assets\Branding\R3_Logo.png" />
    <None Include="Assets\Branding\R3_Logo.svg" />
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
