<Project>
  <PropertyGroup>
    <AssemblyName>R3.Desktop</AssemblyName>
    <IntermediateOutputPath>obj\Debug\</IntermediateOutputPath>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\</MSBuildProjectExtensionsPath>
    <_TargetAssemblyProjectName>R3.Desktop</_TargetAssemblyProjectName>
    <RootNamespace>R3.Desktop</RootNamespace>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <ItemGroup>
    <ProjectReference Include="..\R3.Application\R3.Application.csproj" />
    <ProjectReference Include="..\R3.Contracts\R3.Contracts.csproj" />
    <ProjectReference Include="..\R3.Infrastructure\R3.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="WPF-UI" />
    <PackageReference Include="CefSharp.Wpf.NETCore" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Dirkster.AvalonDock" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.Aero" />
    <PackageReference Include="Fluent.Ribbon" />
    <PackageReference Include="HandyControl" />
    <PackageReference Include="Krypton.Toolkit" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="FastReport.OpenSource" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\AR3.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\Accessibility.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\dirkster.avalondock\4.72.1\lib\net5.0-windows7.0\AvalonDock.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\dirkster.avalondock.themes.aero\4.72.1\lib\net5.0-windows7.0\AvalonDock.Themes.Aero.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\azure.core\1.47.1\lib\net8.0\Azure.Core.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\azure.identity\1.14.2\lib\net8.0\Azure.Identity.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\cefsharp.common.netcore\151.3.240\ref\net6.0\CefSharp.Core.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\cefsharp.common.netcore\151.3.240\ref\net6.0\CefSharp.Core.Runtime.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\cefsharp.common.netcore\151.3.240\ref\net6.0\CefSharp.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\cefsharp.wpf.netcore\151.3.240\ref\net6.0-windows7.0\CefSharp.Wpf.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\closedxml\0.105.1\lib\netstandard2.1\ClosedXML.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\closedxml.parser\2.0.0\lib\netstandard2.1\ClosedXML.Parser.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\communitytoolkit.mvvm\8.4.2\lib\net8.0\CommunityToolkit.Mvvm.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\controlzex\7.0.3\lib\net8.0-windows7.0\ControlzEx.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\dapper\2.1.86\lib\net10.0\Dapper.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\documentformat.openxml\3.5.1\lib\net10.0\DocumentFormat.OpenXml.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\documentformat.openxml.framework\3.5.1\lib\net10.0\DocumentFormat.OpenXml.Framework.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\excelnumberformat\1.1.0\lib\netstandard2.0\ExcelNumberFormat.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\fastreport.compat\2026.2.8\lib\net6.0-windows7.0\FastReport.Compat.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\fastreport.opensource\2026.2.8\lib\net6.0-windows7.0\FastReport.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\fluent.ribbon\11.0.2\lib\net8.0-windows7.0\Fluent.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\fluentvalidation\12.1.1\lib\net8.0\FluentValidation.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\handycontrol\3.5.1\lib\net8.0\HandyControl.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\krypton.toolkit\105.26.7.201\lib\net10.0-windows7.0\Krypton.Toolkit.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.bcl.asyncinterfaces\8.0.0\lib\netstandard2.1\Microsoft.Bcl.AsyncInterfaces.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.bcl.cryptography\9.0.4\lib\net9.0\Microsoft.Bcl.Cryptography.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.codeanalysis.csharp\4.0.1\lib\netcoreapp3.1\Microsoft.CodeAnalysis.CSharp.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.codeanalysis.common\4.0.1\lib\netcoreapp3.1\Microsoft.CodeAnalysis.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.codeanalysis.visualbasic\4.0.1\lib\netcoreapp3.1\Microsoft.CodeAnalysis.VisualBasic.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\Microsoft.CSharp.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.data.sqlclient\6.1.2\ref\net9.0\Microsoft.Data.SqlClient.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.data.sqlite.core\10.0.12\lib\net8.0\Microsoft.Data.Sqlite.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.entityframeworkcore.abstractions\10.0.12\lib\net10.0\Microsoft.EntityFrameworkCore.Abstractions.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.entityframeworkcore\10.0.12\lib\net10.0\Microsoft.EntityFrameworkCore.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.entityframeworkcore.relational\10.0.12\lib\net10.0\Microsoft.EntityFrameworkCore.Relational.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.entityframeworkcore.sqlite.core\10.0.12\lib\net10.0\Microsoft.EntityFrameworkCore.Sqlite.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.extensions.caching.abstractions\10.0.12\lib\net10.0\Microsoft.Extensions.Caching.Abstractions.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.extensions.caching.memory\10.0.12\lib\net10.0\Microsoft.Extensions.Caching.Memory.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.extensions.configuration.abstractions\10.0.12\lib\net10.0\Microsoft.Extensions.Configuration.Abstractions.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\10.0.12\lib\net10.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.extensions.dependencyinjection\10.0.12\lib\net10.0\Microsoft.Extensions.DependencyInjection.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.extensions.dependencymodel\10.0.12\lib\net10.0\Microsoft.Extensions.DependencyModel.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.extensions.logging.abstractions\10.0.12\lib\net10.0\Microsoft.Extensions.Logging.Abstractions.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.extensions.logging\10.0.12\lib\net10.0\Microsoft.Extensions.Logging.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.extensions.options\10.0.12\lib\net10.0\Microsoft.Extensions.Options.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.extensions.primitives\10.0.12\lib\net10.0\Microsoft.Extensions.Primitives.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.identity.client\4.73.1\lib\net8.0\Microsoft.Identity.Client.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.identity.client.extensions.msal\4.73.1\lib\net8.0\Microsoft.Identity.Client.Extensions.Msal.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.identitymodel.abstractions\7.7.1\lib\net8.0\Microsoft.IdentityModel.Abstractions.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.identitymodel.jsonwebtokens\7.7.1\lib\net8.0\Microsoft.IdentityModel.JsonWebTokens.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.identitymodel.logging\7.7.1\lib\net8.0\Microsoft.IdentityModel.Logging.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.identitymodel.protocols\7.7.1\lib\net8.0\Microsoft.IdentityModel.Protocols.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.identitymodel.protocols.openidconnect\7.7.1\lib\net8.0\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.identitymodel.tokens\7.7.1\lib\net8.0\Microsoft.IdentityModel.Tokens.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.sqlserver.server\1.0.0\lib\netstandard2.0\Microsoft.SqlServer.Server.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\Microsoft.VisualBasic.Core.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\Microsoft.VisualBasic.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\Microsoft.VisualBasic.Forms.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\Microsoft.Win32.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\Microsoft.Win32.Registry.AccessControl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\Microsoft.Win32.Registry.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\Microsoft.Win32.SystemEvents.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\microsoft.xaml.behaviors.wpf\1.1.135\lib\net6.0-windows7.0\Microsoft.Xaml.Behaviors.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\mscorlib.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\netstandard.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\npgsql\10.0.3\lib\net10.0\Npgsql.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\npgsql.entityframeworkcore.postgresql\10.0.3\lib\net10.0\Npgsql.EntityFrameworkCore.PostgreSQL.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\PresentationCore.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\PresentationFramework.Aero.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\PresentationFramework.Aero2.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\PresentationFramework.AeroLite.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\PresentationFramework.Classic.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\PresentationFramework.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\PresentationFramework.Luna.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\PresentationFramework.Royale.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\PresentationUI.dll" />
    <ReferencePath Include="C:\Users\mesud\AppData\Local\Temp\claude\c--Users-mesud-source-repos-R3\d3ae8328-6281-4a88-9762-7f9d595af99c\scratchpad\tbuild\R3.Application.dll" />
    <ReferencePath Include="C:\Users\mesud\AppData\Local\Temp\claude\c--Users-mesud-source-repos-R3\d3ae8328-6281-4a88-9762-7f9d595af99c\scratchpad\tbuild\R3.Contracts.dll" />
    <ReferencePath Include="C:\Users\mesud\AppData\Local\Temp\claude\c--Users-mesud-source-repos-R3\d3ae8328-6281-4a88-9762-7f9d595af99c\scratchpad\tbuild\R3.Domain.dll" />
    <ReferencePath Include="C:\Users\mesud\AppData\Local\Temp\claude\c--Users-mesud-source-repos-R3\d3ae8328-6281-4a88-9762-7f9d595af99c\scratchpad\tbuild\R3.Infrastructure.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\rbush.signed\4.0.0\lib\net8.0\RBush.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\ReachFramework.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\serilog\4.4.0\lib\net10.0\Serilog.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\serilog.extensions.logging\10.0.0\lib\net10.0\Serilog.Extensions.Logging.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\serilog.sinks.file\7.0.0\lib\net9.0\Serilog.Sinks.File.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\sixlabors.fonts\1.0.0\lib\netcoreapp3.1\SixLabors.Fonts.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\sqlitepclraw.config.e_sqlite3\3.0.5\lib\net8.0\SQLitePCLRaw.batteries_v2.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\sqlitepclraw.core\3.0.5\lib\net8.0\SQLitePCLRaw.core.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\sqlitepclraw.provider.e_sqlite3\3.0.5\lib\net8.0-windows7.0\SQLitePCLRaw.provider.e_sqlite3.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.AppContext.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Buffers.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\system.clientmodel\1.5.1\lib\net8.0\System.ClientModel.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.CodeDom.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Collections.Concurrent.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Collections.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Collections.Immutable.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Collections.NonGeneric.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Collections.Specialized.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.ComponentModel.Annotations.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.ComponentModel.DataAnnotations.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.ComponentModel.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.ComponentModel.EventBasedAsync.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.ComponentModel.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.ComponentModel.TypeConverter.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Configuration.ConfigurationManager.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Configuration.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Console.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Core.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Data.Common.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Data.DataSetExtensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Data.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Design.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Diagnostics.Contracts.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Diagnostics.Debug.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Diagnostics.DiagnosticSource.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Diagnostics.EventLog.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Diagnostics.FileVersionInfo.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Diagnostics.PerformanceCounter.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Diagnostics.Process.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Diagnostics.StackTrace.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Diagnostics.TextWriterTraceListener.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Diagnostics.Tools.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Diagnostics.TraceSource.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Diagnostics.Tracing.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.DirectoryServices.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Drawing.Common.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Drawing.Design.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Drawing.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Drawing.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Dynamic.Runtime.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Formats.Asn1.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Formats.Nrbf.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Formats.Tar.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Globalization.Calendars.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Globalization.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Globalization.Extensions.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\system.identitymodel.tokens.jwt\7.7.1\lib\net8.0\System.IdentityModel.Tokens.Jwt.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.Compression.Brotli.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.Compression.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.Compression.FileSystem.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.Compression.ZipFile.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.FileSystem.AccessControl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.FileSystem.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.FileSystem.DriveInfo.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.FileSystem.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.FileSystem.Watcher.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.IsolatedStorage.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.MemoryMappedFiles.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.IO.Packaging.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.Pipelines.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.Pipes.AccessControl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.Pipes.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.IO.UnmanagedMemoryStream.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Linq.AsyncEnumerable.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Linq.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Linq.Expressions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Linq.Parallel.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Linq.Queryable.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\system.memory.data\8.0.1\lib\net8.0\System.Memory.Data.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Memory.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.Http.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.Http.Json.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.HttpListener.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.Mail.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.NameResolution.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.NetworkInformation.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.Ping.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.Quic.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.Requests.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.Security.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.ServerSentEvents.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.ServicePoint.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.Sockets.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.WebClient.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.WebHeaderCollection.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.WebProxy.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.WebSockets.Client.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Net.WebSockets.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Numerics.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Numerics.Vectors.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.ObjectModel.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Printing.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Private.Windows.Core.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Private.Windows.GdiPlus.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Reflection.DispatchProxy.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Reflection.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Reflection.Emit.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Reflection.Emit.ILGeneration.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Reflection.Emit.Lightweight.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Reflection.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Reflection.Metadata.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Reflection.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Reflection.TypeExtensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Resources.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Resources.Reader.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Resources.ResourceManager.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Resources.Writer.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.CompilerServices.Unsafe.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.CompilerServices.VisualC.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.Handles.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.InteropServices.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.InteropServices.JavaScript.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.InteropServices.RuntimeInformation.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.Intrinsics.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.Loader.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.Numerics.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.Serialization.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.Serialization.Formatters.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.Serialization.Json.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.Serialization.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Runtime.Serialization.Xml.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.AccessControl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.Claims.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.Cryptography.Algorithms.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.Cryptography.Cng.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.Cryptography.Csp.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.Cryptography.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.Cryptography.Encoding.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.Cryptography.OpenSsl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Security.Cryptography.Pkcs.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.Cryptography.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Security.Cryptography.ProtectedData.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.Cryptography.X509Certificates.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Security.Cryptography.Xml.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Security.Permissions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.Principal.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.Principal.Windows.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Security.SecureString.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.ServiceModel.Web.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.ServiceProcess.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Text.Encoding.CodePages.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Text.Encoding.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Text.Encoding.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Text.Encodings.Web.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Text.Json.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Text.RegularExpressions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Threading.AccessControl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Threading.Channels.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Threading.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Threading.Overlapped.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Threading.Tasks.Dataflow.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Threading.Tasks.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Threading.Tasks.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Threading.Tasks.Parallel.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Threading.Thread.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Threading.ThreadPool.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Threading.Timer.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Transactions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Transactions.Local.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.ValueTuple.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Web.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Web.HttpUtility.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Windows.Controls.Ribbon.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Windows.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Windows.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Windows.Forms.Design.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Windows.Forms.Design.Editors.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Windows.Forms.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Windows.Forms.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Windows.Input.Manipulations.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Windows.Presentation.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Windows.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\System.Xaml.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Xml.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Xml.Linq.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Xml.ReaderWriter.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Xml.Serialization.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Xml.XDocument.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Xml.XmlDocument.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Xml.XmlSerializer.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Xml.XPath.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\ref\net10.0\System.Xml.XPath.XDocument.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\UIAutomationClient.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\UIAutomationClientSideProviders.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\UIAutomationProvider.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\UIAutomationTypes.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\WindowsBase.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\ref\net10.0\WindowsFormsIntegration.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\wpf-ui.abstractions\4.3.0\lib\net10.0\Wpf.Ui.Abstractions.dll" />
    <ReferencePath Include="C:\Users\mesud\.nuget\packages\wpf-ui\4.3.0\lib\net10.0-windows7.0\Wpf.Ui.dll" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\MainWindow.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\AccountAddressEditDialog.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\AccountAddressesContactsView.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\AccountBankEditDialog.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\AccountContactEditDialog.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\AccountEditDialog.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\AccountNoteEditDialog.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\AccountStatementView.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\AccountsView.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\AccountTransactionsView.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\CashAccountEditDialog.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\CashAccountsView.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\CashInOutDialog.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\CashStatementView.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\CashTransactionsView.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\CashTransferDialog.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\CreditRiskView.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\CustomerFinderDialog.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\CustomerWorkspaceView.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\InstallmentCollectionDialog.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\ManualLedgerEntryDialog.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\ReceiptPaymentDialog.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\Views\StockCardWindow.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\App.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\R3.Desktop_Content.g.cs" />
    <Compile Include="C:\Users\mesud\source\repos\R3\src\R3.Desktop\obj\Debug\net10.0-windows\win-x64\GeneratedInternalTypeHelper.g.cs" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="C:\Program Files\dotnet\sdk\10.0.401\Sdks\Microsoft.NET.Sdk\targets\..\analyzers\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll" />
    <Analyzer Include="C:\Program Files\dotnet\sdk\10.0.401\Sdks\Microsoft.NET.Sdk\targets\..\analyzers\Microsoft.CodeAnalysis.NetAnalyzers.dll" />
    <Analyzer Include="C:\Users\mesud\.nuget\packages\communitytoolkit.mvvm\8.4.2\analyzers\dotnet\roslyn5.0\cs\CommunityToolkit.Mvvm.CodeFixers.dll" />
    <Analyzer Include="C:\Users\mesud\.nuget\packages\communitytoolkit.mvvm\8.4.2\analyzers\dotnet\roslyn5.0\cs\CommunityToolkit.Mvvm.SourceGenerators.dll" />
    <Analyzer Include="C:\Users\mesud\.nuget\packages\microsoft.codeanalysis.analyzers\3.3.2\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll" />
    <Analyzer Include="C:\Users\mesud\.nuget\packages\microsoft.codeanalysis.analyzers\3.3.2\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll" />
    <Analyzer Include="C:\Users\mesud\.nuget\packages\microsoft.entityframeworkcore.analyzers\10.0.12\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll" />
    <Analyzer Include="C:\Users\mesud\.nuget\packages\microsoft.extensions.logging.abstractions\10.0.12\analyzers\dotnet\roslyn4.4\cs\Microsoft.Extensions.Logging.Generators.dll" />
    <Analyzer Include="C:\Users\mesud\.nuget\packages\microsoft.extensions.options\10.0.12\analyzers\dotnet\roslyn4.4\cs\Microsoft.Extensions.Options.SourceGeneration.dll" />
    <Analyzer Include="C:\Users\mesud\.nuget\packages\system.clientmodel\1.5.1\analyzers\dotnet\cs\System.ClientModel.SourceGeneration.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\analyzers/dotnet/cs/Microsoft.Interop.ComInterfaceGenerator.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\analyzers/dotnet/cs/Microsoft.Interop.JavaScript.JSImportGenerator.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\analyzers/dotnet/cs/Microsoft.Interop.LibraryImportGenerator.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\analyzers/dotnet/cs/Microsoft.Interop.SourceGeneration.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\10.0.12\analyzers/dotnet/cs/System.Text.RegularExpressions.Generator.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\analyzers/dotnet/System.Windows.Forms.Analyzers.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\analyzers/dotnet/cs/System.Windows.Forms.Analyzers.CSharp.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.12\analyzers/dotnet/cs/System.Windows.Forms.Analyzers.CodeFixes.CSharp.dll" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>