using Krypton.Toolkit;
using R3.Application.Authentication;
using R3.Application.Transactions;
using R3.Desktop.Branding;
using R3.Desktop.Theme;

namespace R3.Desktop.Dialogs;

internal sealed class InvoiceEditorDialog:IAsyncDisposable
{
 private readonly KryptonForm _form=new();private readonly ITradeTransactionService _service;private readonly UserSessionData _session;private readonly InvoiceListItem? _edit;
 private readonly KryptonComboBox _type=new(),_account=new(),_currency=new(),_warehouse=new();private readonly KryptonTextBox _number=new(),_documentNumber=new(),_dispatchNumber=new(),_taxNumber=new(){ReadOnly=true},_description=new();
 private readonly KryptonDateTimePicker _date=new(),_due=new(),_dispatchDate=new(){ShowCheckBox=true,Checked=false};private readonly KryptonNumericUpDown _rate=new(){DecimalPlaces=4,Maximum=1000000,Value=1};
 private readonly DataGridView _lines=new();private TradeLookups _lookups=null!;private readonly Label _message=new();private KryptonButton _save=null!;
 public InvoiceEditorDialog(ITradeTransactionService service,UserSessionData session,InvoiceListItem? edit=null){_service=service;_session=session;_edit=edit;Build();}
 public async Task<DialogResult> ShowAsync(IWin32Window owner){await LoadAsync();return _form.ShowDialog(owner);}
 private void Build()
 {
  _form.Text=_edit is null?"R3 • Yeni Satış / Alış Faturası":$"R3 • Fatura Güncelle • {_edit.InvoiceNumber}";_form.Icon=R3Branding.AppIcon;_form.StartPosition=FormStartPosition.CenterParent;_form.ClientSize=new Size(1280,790);_form.MinimumSize=new Size(1100,700);
  var title=new Panel{Dock=DockStyle.Top,Height=64,BackColor=Color.FromArgb(20,43,72),Padding=new Padding(20,10,20,8)};title.Controls.Add(new Label{Text="FATURA BELGESİ",Dock=DockStyle.Top,Height=25,ForeColor=Color.White,Font=new Font("Segoe UI",14,FontStyle.Bold)});title.Controls.Add(new Label{Text="Belge, cari, vergi ve ürün satırlarını tek ekrandan yönetin",Dock=DockStyle.Bottom,Height=20,ForeColor=Color.FromArgb(190,210,232),Font=new Font("Segoe UI",8.5F)});
  var head=new TableLayoutPanel{Dock=DockStyle.Top,Height=246,ColumnCount=5,RowCount=8,Padding=new Padding(18,8,18,8),BackColor=Color.White};for(int i=0;i<5;i++)head.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,20));
  _type.DataSource=new[]{"Satış Faturası","Satış İade","Alış Faturası","Alış İade"};_currency.DataSource=new[]{"TRY","USD","EUR","GBP"};
  Field(head,0,0,"Fatura Türü",_type);Field(head,1,0,"Fatura Numarası",_number);Field(head,2,0,"Belge Numarası",_documentNumber);Field(head,3,0,"Fatura Tarihi",_date);Field(head,4,0,"Vade Tarihi",_due);
  Field(head,0,1,"Cari Hesap",_account,2);Field(head,2,1,"Vergi / T.C. No",_taxNumber);Field(head,3,1,"İrsaliye Numarası",_dispatchNumber);Field(head,4,1,"İrsaliye Tarihi",_dispatchDate);
  Field(head,0,2,"Depo",_warehouse);Field(head,1,2,"Para Birimi",_currency);Field(head,2,2,"Döviz Kuru",_rate);Field(head,3,2,"Açıklama",_description,2);
  _account.SelectedIndexChanged+=(_,_)=>_taxNumber.Text=(_account.SelectedItem as TradeLookup)?.Detail??"Vergi bilgisi tanımlı değil";
  _lines.Dock=DockStyle.Fill;_lines.AutoGenerateColumns=false;_lines.AllowUserToAddRows=true;_lines.RowHeadersVisible=false;_lines.BackgroundColor=Color.White;_lines.BorderStyle=BorderStyle.None;_lines.CellBorderStyle=DataGridViewCellBorderStyle.SingleHorizontal;_lines.GridColor=Color.FromArgb(226,232,240);_lines.RowTemplate.Height=36;_lines.ColumnHeadersHeight=40;_lines.EnableHeadersVisualStyles=false;_lines.ColumnHeadersDefaultCellStyle.BackColor=Color.FromArgb(241,245,249);_lines.ColumnHeadersDefaultCellStyle.ForeColor=Color.FromArgb(51,65,85);_lines.ColumnHeadersDefaultCellStyle.Font=new Font("Segoe UI Semibold",8.5F);_lines.DefaultCellStyle.SelectionBackColor=Color.FromArgb(219,234,254);_lines.DefaultCellStyle.SelectionForeColor=Color.FromArgb(15,23,42);_lines.AlternatingRowsDefaultCellStyle.BackColor=Color.FromArgb(248,250,252);
  _lines.Columns.Add(new DataGridViewComboBoxColumn{Name="Product",DataPropertyName="ProductId",HeaderText="ÜRÜN",Width=260,DisplayMember="Display",ValueMember="Id"});
  _lines.Columns.Add(new DataGridViewTextBoxColumn{Name="VariantId",Visible=false});_lines.Columns.Add(new DataGridViewTextBoxColumn{Name="UnitId",Visible=false});_lines.Columns.Add(new DataGridViewTextBoxColumn{Name="WarehouseId",Visible=false});
  Col("Quantity","MİKTAR",90);Col("UnitPrice","BİRİM FİYAT",110);Col("DiscountRate","İSKONTO %",90);Col("VatRate","KDV %",75);Col("Description","AÇIKLAMA",220);
  var footer=new Panel{Dock=DockStyle.Bottom,Height=58,BackColor=Color.White,Padding=new Padding(14,10,14,10)};_save=R3Theme.CreatePrimaryButton(_edit is null?"Faturayı Kaydet":"Faturayı Güncelle");_save.Dock=DockStyle.Right;_save.Width=130;_save.Click+=async(_,_)=>await SaveAsync();
  var cancel=new KryptonButton{Text="Vazgeç",Dock=DockStyle.Right,Width=90};cancel.Click+=(_,_)=>_form.DialogResult=DialogResult.Cancel;_message.Dock=DockStyle.Fill;_message.ForeColor=Color.Firebrick;footer.Controls.Add(_message);footer.Controls.Add(cancel);footer.Controls.Add(_save);
  _form.Controls.Add(_lines);_form.Controls.Add(footer);_form.Controls.Add(head);_form.Controls.Add(title);_form.AcceptButton=_save;_form.CancelButton=cancel;
 }
 private async Task LoadAsync(){_lookups=await _service.GetLookupsAsync(_session.CompanyId,_session.BranchId);Bind(_account,_lookups.Accounts);Bind(_warehouse,_lookups.Warehouses);if(_lines.Columns["Product"] is DataGridViewComboBoxColumn productColumn)productColumn.DataSource=_lookups.Products.ToList();if(_edit is null)return;var detail=await _service.GetInvoiceDetailAsync(_edit.InvoiceId,_session.CompanyId)??throw new InvalidOperationException("Fatura bulunamadı.");_number.Text=detail.InvoiceNumber;_documentNumber.Text=detail.DocumentNumber??"";_dispatchNumber.Text=detail.DispatchNumber??"";if(detail.DispatchDate.HasValue){_dispatchDate.Checked=true;_dispatchDate.Value=detail.DispatchDate.Value;}_date.Value=detail.InvoiceDate;_due.Value=detail.DueDate;_currency.SelectedItem=detail.CurrencyCode;_rate.Value=detail.ExchangeRate;_description.Text=detail.Description??"";_account.SelectedValue=detail.AccountId;_type.SelectedIndex=detail.InvoiceType-1;foreach(var line in detail.Lines){int i=_lines.Rows.Add();var row=_lines.Rows[i];row.Cells["Product"].Value=line.ProductId;row.Cells["VariantId"].Value=line.VariantId;row.Cells["UnitId"].Value=line.UnitId;row.Cells["WarehouseId"].Value=line.WarehouseId;row.Cells["Quantity"].Value=line.Quantity;row.Cells["UnitPrice"].Value=line.UnitPrice;row.Cells["DiscountRate"].Value=line.DiscountRate;row.Cells["VatRate"].Value=line.VatRate;row.Cells["Description"].Value=line.Description;if(line.WarehouseId.HasValue)_warehouse.SelectedValue=(long)line.WarehouseId.Value;}bool editable=detail.Status==1;_lines.ReadOnly=!editable;_save.Enabled=editable;if(!editable)_message.Text="Onaylı veya iptal edilmiş belge salt okunur açıldı.";}
 private async Task SaveAsync(){try{if(_warehouse.SelectedValue is null){_message.Text="Depo zorunludur.";return;}var lines=new List<InvoiceLineSaveRequest>();foreach(DataGridViewRow row in _lines.Rows){if(row.IsNewRow||row.Cells["Product"].Value is null)continue;long? variant=row.Cells["VariantId"].Value is null?null:Convert.ToInt64(row.Cells["VariantId"].Value,System.Globalization.CultureInfo.InvariantCulture);int unit=row.Cells["UnitId"].Value is null?0:Convert.ToInt32(row.Cells["UnitId"].Value,System.Globalization.CultureInfo.InvariantCulture);int warehouse=row.Cells["WarehouseId"].Value is null?Convert.ToInt32(_warehouse.SelectedValue,System.Globalization.CultureInfo.InvariantCulture):Convert.ToInt32(row.Cells["WarehouseId"].Value,System.Globalization.CultureInfo.InvariantCulture);lines.Add(new(Convert.ToInt64(row.Cells["Product"].Value,System.Globalization.CultureInfo.InvariantCulture),variant,unit,warehouse,D(row,"Quantity"),D(row,"UnitPrice"),D(row,"DiscountRate"),D(row,"VatRate"),row.Cells["Description"].Value?.ToString()));}if(lines.Count==0){_message.Text="Faturada en az bir satır olmalıdır.";return;}if(_account.SelectedValue is null){_message.Text="Cari hesap zorunludur.";return;}var x=new InvoiceSaveRequest(_edit?.InvoiceId,_session.CompanyId,_session.BranchId,_lookups.FiscalPeriodId,_session.UserId,(byte)(_type.SelectedIndex+1),_number.Text.Trim(),Null(_documentNumber.Text),Null(_dispatchNumber.Text),_dispatchDate.Checked?_dispatchDate.Value.Date:null,_date.Value,_due.Value,Convert.ToInt64(_account.SelectedValue,System.Globalization.CultureInfo.InvariantCulture),_currency.Text,_rate.Value,_description.Text,lines);await _service.SaveInvoiceAsync(x);_form.DialogResult=DialogResult.OK;_form.Close();}catch(Exception ex){_message.Text=ex.Message;}}
 private static decimal D(DataGridViewRow r,string n)=>decimal.TryParse(r.Cells[n].Value?.ToString(),out var x)?x:0;
 private static string? Null(string value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();
 private void Col(string n,string h,int w)=>_lines.Columns.Add(new DataGridViewTextBoxColumn{Name=n,DataPropertyName=n,HeaderText=h,Width=w});
 private static void Bind(KryptonComboBox c,IReadOnlyList<TradeLookup> x){c.DataSource=x.ToList();c.DisplayMember="Display";c.ValueMember="Id";c.DropDownStyle=ComboBoxStyle.DropDownList;}
 private static void Field(TableLayoutPanel t,int c,int r,string l,Control x,int span=1){t.Controls.Add(new Label{Text=l,Dock=DockStyle.Fill,ForeColor=R3Colors.MutedText,TextAlign=ContentAlignment.BottomLeft,Font=new Font("Segoe UI",8,FontStyle.Bold)},c,r*2);x.Dock=DockStyle.Fill;x.Margin=new Padding(0,3,10,4);t.Controls.Add(x,c,r*2+1);if(span>1)t.SetColumnSpan(x,span);}
 public ValueTask DisposeAsync(){_form.Dispose();return ValueTask.CompletedTask;}
}

internal sealed class FinanceEditorDialog:IAsyncDisposable
{
 private readonly KryptonForm _form=new();private readonly ITradeTransactionService _service;private readonly UserSessionData _session;private readonly FinanceListItem? _edit;
 private readonly KryptonComboBox _type=new(),_account=new(),_targetType=new(),_target=new(),_currency=new();private readonly KryptonTextBox _number=new(),_reference=new(),_description=new();
 private readonly KryptonDateTimePicker _date=new();private readonly KryptonNumericUpDown _amount=new(){DecimalPlaces=2,Maximum=100000000,ThousandsSeparator=true},_rate=new(){DecimalPlaces=4,Maximum=1000000,Value=1};private readonly Label _message=new();private TradeLookups _lookups=null!;
 public FinanceEditorDialog(ITradeTransactionService service,UserSessionData session,FinanceListItem? edit=null){_service=service;_session=session;_edit=edit;Build();}
 public async Task<DialogResult> ShowAsync(IWin32Window owner){await LoadAsync();return _form.ShowDialog(owner);}
 private void Build(){_form.Text=_edit is null?"R3 • Yeni Finans İşlemi":$"R3 • Finans Güncelle • {_edit.DocumentNumber}";_form.Icon=R3Branding.AppIcon;_form.StartPosition=FormStartPosition.CenterParent;_form.ClientSize=new Size(780,520);
  var t=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,Padding=new Padding(24),BackColor=Color.White};t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));
  _type.DataSource=new[]{"Tahsilat","Ödeme","Kasa Giriş","Kasa Çıkış","Banka Giriş","Banka Çıkış"};_targetType.DataSource=new[]{"Kasa","Banka"};_currency.DataSource=new[]{"TRY","USD","EUR","GBP"};_targetType.SelectedIndexChanged+=(_,_)=>BindTarget();
  F(t,0,0,"İşlem Türü",_type);F(t,1,0,"Belge Numarası",_number);F(t,0,1,"İşlem Tarihi",_date);F(t,1,1,"Cari Hesap",_account);F(t,0,2,"Hesap Türü",_targetType);F(t,1,2,"Kasa / Banka",_target);F(t,0,3,"Tutar",_amount);F(t,1,3,"Para Birimi",_currency);F(t,0,4,"Döviz Kuru",_rate);F(t,1,4,"Referans",_reference);F(t,0,5,"Açıklama",_description,2);
  var footer=new Panel{Dock=DockStyle.Bottom,Height=58,Padding=new Padding(14,10,14,10),BackColor=Color.White};var save=R3Theme.CreatePrimaryButton(_edit is null?"İşlemi Kaydet":"İşlemi Güncelle");save.Dock=DockStyle.Right;save.Width=130;save.Click+=async(_,_)=>await SaveAsync();_message.Dock=DockStyle.Fill;_message.ForeColor=Color.Firebrick;footer.Controls.Add(_message);footer.Controls.Add(save);_form.Controls.Add(t);_form.Controls.Add(footer);}
 private async Task LoadAsync(){_lookups=await _service.GetLookupsAsync(_session.CompanyId,_session.BranchId);Bind(_account,_lookups.Accounts,true);BindTarget();if(_edit is not null){_number.Text=_edit.DocumentNumber;_date.Value=_edit.TransactionDate;_amount.Value=_edit.Amount;_currency.SelectedItem=_edit.CurrencyCode;_reference.Text=_edit.ReferenceNumber??"";_type.SelectedIndex=_edit.TransactionType switch{"Tahsilat"=>0,"Ödeme"=>1,"Kasa Giriş"=>2,"Kasa Çıkış"=>3,"Banka Giriş"=>4,_=>5};}}
 private void BindTarget(){if(_lookups is null)return;Bind(_target,_targetType.SelectedIndex==0?_lookups.CashAccounts:_lookups.BankAccounts,false);}
 private async Task SaveAsync(){try{if(_target.SelectedValue is null){_message.Text="Kasa veya banka hesabı zorunludur.";return;}int target=Convert.ToInt32(_target.SelectedValue,System.Globalization.CultureInfo.InvariantCulture);var x=new FinanceSaveRequest(_edit?.FinancialTransactionId,_session.CompanyId,_session.BranchId,_lookups.FiscalPeriodId,_session.UserId,(byte)(_type.SelectedIndex+1),_number.Text.Trim(),_date.Value,_account.SelectedValue is long a&&a>0?a:null,_targetType.SelectedIndex==0?target:null,_targetType.SelectedIndex==1?target:null,_currency.Text,_rate.Value,_amount.Value,_reference.Text,_description.Text);await _service.SaveFinanceAsync(x);_form.DialogResult=DialogResult.OK;_form.Close();}catch(Exception ex){_message.Text=ex.Message;}}
 private static void Bind(KryptonComboBox c,IReadOnlyList<TradeLookup> source,bool optional){var x=source.ToList();if(optional)x.Insert(0,new TradeLookup(0,"","Seçilmedi"));c.DataSource=x;c.DisplayMember="Display";c.ValueMember="Id";c.DropDownStyle=ComboBoxStyle.DropDownList;}
 private static void F(TableLayoutPanel t,int c,int r,string l,Control x,int span=1){t.RowStyles.Add(new RowStyle(SizeType.Absolute,24));t.Controls.Add(new Label{Text=l,Dock=DockStyle.Fill,TextAlign=ContentAlignment.BottomLeft,ForeColor=R3Colors.MutedText,Font=new Font("Segoe UI",8,FontStyle.Bold)},c,r*2);x.Dock=DockStyle.Fill;x.Margin=new Padding(0,4,12,6);t.Controls.Add(x,c,r*2+1);if(span>1)t.SetColumnSpan(x,span);}
 public ValueTask DisposeAsync(){_form.Dispose();return ValueTask.CompletedTask;}
}

internal sealed class PaymentAllocationDialog:IAsyncDisposable
{
 private readonly KryptonForm _form=new();private readonly ITradeTransactionService _service;private readonly UserSessionData _session;private readonly InvoiceListItem _invoice;
 private readonly KryptonComboBox _payment=new();private readonly KryptonNumericUpDown _amount=new(){DecimalPlaces=2,Maximum=100000000,ThousandsSeparator=true};private readonly Label _message=new();
 public PaymentAllocationDialog(ITradeTransactionService service,UserSessionData session,InvoiceListItem invoice){_service=service;_session=session;_invoice=invoice;Build();}
 public async Task<DialogResult> ShowAsync(IWin32Window owner){var all=await _service.GetFinanceTransactionsAsync(_session.CompanyId);string required=_invoice.InvoiceType is "Satış" or "Alış İade"?"Tahsilat":"Ödeme";var candidates=all.Where(x=>x.Status=="Onaylı"&&x.TransactionType==required&&x.AccountCode==_invoice.AccountCode).ToList();_payment.DataSource=candidates;_payment.DisplayMember=nameof(FinanceListItem.DocumentNumber);_payment.ValueMember=nameof(FinanceListItem.FinancialTransactionId);_amount.Value=Math.Max(0,_invoice.RemainingTotal);if(candidates.Count==0)_message.Text=$"Bu cari için onaylı {required.ToLowerInvariant()} bulunamadı.";return _form.ShowDialog(owner);}
 private void Build(){_form.Text=$"R3 • Ödeme Eşleştirme • {_invoice.InvoiceNumber}";_form.Icon=R3Branding.AppIcon;_form.StartPosition=FormStartPosition.CenterParent;_form.ClientSize=new Size(520,280);var t=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,Padding=new Padding(24),BackColor=Color.White};t.Controls.Add(new Label{Text=$"Kalan fatura tutarı: {_invoice.RemainingTotal:N2} {_invoice.CurrencyCode}",Dock=DockStyle.Fill,Font=new Font("Segoe UI",10,FontStyle.Bold)});t.Controls.Add(new Label{Text="Onaylı tahsilat / ödeme",Dock=DockStyle.Fill,ForeColor=R3Colors.MutedText});_payment.Dock=DockStyle.Fill;_payment.DropDownStyle=ComboBoxStyle.DropDownList;t.Controls.Add(_payment);t.Controls.Add(new Label{Text="Eşleştirilecek tutar",Dock=DockStyle.Fill,ForeColor=R3Colors.MutedText});_amount.Dock=DockStyle.Fill;t.Controls.Add(_amount);_message.Dock=DockStyle.Fill;_message.ForeColor=Color.Firebrick;t.Controls.Add(_message);var save=R3Theme.CreatePrimaryButton("Eşleştir");save.Dock=DockStyle.Bottom;save.Height=38;save.Click+=async(_,_)=>await SaveAsync();t.Controls.Add(save);_form.Controls.Add(t);}
 private async Task SaveAsync(){try{if(_payment.SelectedValue is null){_message.Text="Onaylı finans işlemi seçilmelidir.";return;}await _service.AllocatePaymentAsync(Convert.ToInt64(_payment.SelectedValue,System.Globalization.CultureInfo.InvariantCulture),_invoice.InvoiceId,_amount.Value,_session.UserId);_form.DialogResult=DialogResult.OK;_form.Close();}catch(Exception ex){_message.Text=ex.Message;}}
 public ValueTask DisposeAsync(){_form.Dispose();return ValueTask.CompletedTask;}
}
