using System.Data;
using Microsoft.Data.Sqlite;

namespace R3.Infrastructure;

public enum InventoryTransactionType { OpeningBalance, PurchaseReceipt, PurchaseReturn, SaleIssue, SaleReturn, TransferOut, TransferIn, CountIncrease, CountDecrease, ManualIn, ManualOut }
public sealed record InventoryPost(string CompanyId, string BranchId, string WarehouseId, string ProductId, string? VariantId, decimal Quantity, decimal? UnitCost, DateTime TransactionAt, string? ReferenceNo = null, string? Description = null);
public sealed record InventoryBalance(string WarehouseId, string ProductId, string? VariantId, decimal QuantityOnHand, decimal QuantityReserved, decimal QuantityAvailable);
public sealed class LocalInventoryService(StoreDatabase database)
{
    public async Task<InventoryBalance?> GetBalanceAsync(string warehouseId, string productId, string? variantId, CancellationToken ct = default)
    { await using var c = Open(); await c.OpenAsync(ct); await using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT warehouse_id,product_id,variant_id,quantity_on_hand,quantity_reserved,quantity_available FROM inventory_balances WHERE warehouse_id=$w AND product_id=$p AND (variant_id=$v OR (variant_id IS NULL AND $v IS NULL))"; Add(cmd, "$w", warehouseId); Add(cmd, "$p", productId); Add(cmd, "$v", (object?)variantId ?? DBNull.Value); await using var r = await cmd.ExecuteReaderAsync(ct); if (!await r.ReadAsync(ct)) return null; return new(r.GetString(0), r.GetString(1), r.IsDBNull(2) ? null : r.GetString(2), r.GetDecimal(3), r.GetDecimal(4), r.GetDecimal(5)); }
    public Task PostOpeningBalanceAsync(InventoryPost post, CancellationToken ct = default) => PostAsync(post, InventoryTransactionType.OpeningBalance, true, ct);
    public Task PostManualInAsync(InventoryPost post, CancellationToken ct = default) => PostAsync(post, InventoryTransactionType.ManualIn, true, ct);
    public Task PostManualOutAsync(InventoryPost post, CancellationToken ct = default) => PostAsync(post, InventoryTransactionType.ManualOut, false, ct);
    public async Task TransferAsync(InventoryPost source, string targetWarehouseId, string targetBranchId, CancellationToken ct = default)
    {
        if (source.WarehouseId == targetWarehouseId) throw new ArgumentException("Kaynak ve hedef depo aynı olamaz."); if (source.Quantity <= 0) throw new ArgumentException("Miktar 0'dan büyük olmalıdır.");
        await using var c = Open(); await c.OpenAsync(ct); await using var tx = c.BeginTransaction(); var correlation = Guid.NewGuid().ToString();
        await ValidateProductAsync(c, tx, source, ct); var current = await BalanceValue(c, tx, source.WarehouseId, source.ProductId, source.VariantId, ct); if (current < source.Quantity) throw new InvalidOperationException($"Yetersiz stok. Kullanılabilir: {current}, istenen: {source.Quantity}.");
        await InsertMovement(c, tx, source, InventoryTransactionType.TransferOut, correlation, ct); await ApplyBalance(c, tx, source, -source.Quantity, ct); var target = source with { WarehouseId = targetWarehouseId, BranchId = targetBranchId }; await InsertMovement(c, tx, target, InventoryTransactionType.TransferIn, correlation, ct); await ApplyBalance(c, tx, target, target.Quantity, ct); await tx.CommitAsync(ct);
    }
    public async Task PostCountAdjustmentAsync(InventoryPost post, decimal counted, CancellationToken ct = default)
    { var current = await GetBalanceAsync(post.WarehouseId, post.ProductId, post.VariantId, ct); var difference = counted - (current?.QuantityOnHand ?? 0); if (difference == 0) return; await PostAsync(post with { Quantity = Math.Abs(difference) }, difference > 0 ? InventoryTransactionType.CountIncrease : InventoryTransactionType.CountDecrease, difference > 0, ct); }
    public async Task<DataTable> SearchBalancesAsync(string? warehouseId = null, string? search = null, CancellationToken ct = default)
    { await using var c = Open(); await c.OpenAsync(ct); await using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT b.warehouse_id AS DepoId,COALESCE(w.name,b.warehouse_id) AS Depo,b.product_id AS UrunId,COALESCE(p.code || ' - ' || p.name,b.product_id) AS Urun,COALESCE(b.variant_id,'') AS Varyant,b.quantity_on_hand AS Mevcut,b.quantity_reserved AS Rezerve,b.quantity_available AS Kullanilabilir,b.last_transaction_at AS SonHareket FROM inventory_balances b LEFT JOIN warehouses w ON w.id=b.warehouse_id LEFT JOIN products p ON p.id=b.product_id WHERE ($w='' OR b.warehouse_id=$w) AND ($q='' OR p.code LIKE $q OR p.name LIKE $q OR b.product_id LIKE $q) ORDER BY p.code"; Add(cmd, "$w", warehouseId ?? ""); Add(cmd, "$q", $"%{search ?? ""}%"); await using var reader = await cmd.ExecuteReaderAsync(ct); var table = new DataTable(); table.Load(reader); return table; }
    public async Task<DataTable> SearchMovementsAsync(string? warehouseId = null, string? search = null, CancellationToken ct = default)
    { await using var c = Open(); await c.OpenAsync(ct); await using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT t.transaction_at AS Tarih,t.reference_no AS Referans,COALESCE(p.code || ' - ' || p.name,t.product_id) AS Urun,COALESCE(t.variant_id,'') AS Varyant,COALESCE(br.name,t.branch_id) AS Sube,COALESCE(w.name,t.warehouse_id) AS Depo,t.transaction_type AS Tur,t.quantity AS Miktar,t.unit_cost AS BirimMaliyet,t.correlation_id AS Korelasyon,t.description AS Aciklama FROM inventory_transactions t LEFT JOIN products p ON p.id=t.product_id LEFT JOIN branches br ON br.id=t.branch_id LEFT JOIN warehouses w ON w.id=t.warehouse_id WHERE ($w='' OR t.warehouse_id=$w) AND ($q='' OR p.code LIKE $q OR p.name LIKE $q OR t.reference_no LIKE $q OR t.description LIKE $q) ORDER BY t.transaction_at DESC,t.created_at DESC"; Add(cmd, "$w", warehouseId ?? ""); Add(cmd, "$q", $"%{search ?? ""}%"); await using var reader = await cmd.ExecuteReaderAsync(ct); var table = new DataTable(); table.Load(reader); return table; }
    public async Task RebuildInventoryBalancesAsync(CancellationToken ct = default)
    { await using var c = Open(); await c.OpenAsync(ct); await using var tx = c.BeginTransaction(); await using (var clear = c.CreateCommand()) { clear.Transaction = tx; clear.CommandText = "DELETE FROM inventory_balances"; await clear.ExecuteNonQueryAsync(ct); } await using var read = c.CreateCommand(); read.Transaction = tx; read.CommandText = "SELECT company_id,branch_id,warehouse_id,product_id,variant_id,transaction_type,quantity,transaction_at FROM inventory_transactions ORDER BY transaction_at,id"; var rows = new DataTable(); await using (var reader = await read.ExecuteReaderAsync(ct)) rows.Load(reader); foreach (DataRow row in rows.Rows) { var sign = IsInbound(row["transaction_type"].ToString()!) ? 1m : -1m; var post = new InventoryPost(row["company_id"].ToString()!, row["branch_id"].ToString()!, row["warehouse_id"].ToString()!, row["product_id"].ToString()!, row["variant_id"] == DBNull.Value ? null : row["variant_id"].ToString(), Convert.ToDecimal(row["quantity"]), null, DateTime.Parse(row["transaction_at"].ToString()!)); await ApplyBalance(c, tx, post, sign * post.Quantity, ct); } await tx.CommitAsync(ct); }
    private async Task PostAsync(InventoryPost post, InventoryTransactionType type, bool inbound, CancellationToken ct)
    { if (post.Quantity <= 0) throw new ArgumentException("Miktar 0'dan büyük olmalıdır."); await using var c = Open(); await c.OpenAsync(ct); await using var tx = c.BeginTransaction(); await ValidateProductAsync(c, tx, post, ct); if (!inbound && await BalanceValue(c, tx, post.WarehouseId, post.ProductId, post.VariantId, ct) < post.Quantity) throw new InvalidOperationException("Yetersiz stok."); await InsertMovement(c, tx, post, type, null, ct); await ApplyBalance(c, tx, post, inbound ? post.Quantity : -post.Quantity, ct); await tx.CommitAsync(ct); }
    private async Task ValidateProductAsync(SqliteConnection c, SqliteTransaction tx, InventoryPost p, CancellationToken ct)
    { await using var cmd = c.CreateCommand(); cmd.Transaction = tx; cmd.CommandText = "SELECT product_type,is_active FROM products WHERE id=$p AND company_id=$c"; Add(cmd, "$p", p.ProductId); Add(cmd, "$c", p.CompanyId); await using var r = await cmd.ExecuteReaderAsync(ct); if (!await r.ReadAsync(ct)) throw new InvalidOperationException("Ürün bulunamadı veya firma kapsamında değil."); if (!r.GetBoolean(1)) throw new InvalidOperationException("Pasif ürün için stok hareketi oluşturulamaz."); if (r.GetString(0).Equals("Service", StringComparison.OrdinalIgnoreCase)) throw new InvalidOperationException("Hizmet ürünü için stok hareketi oluşturulamaz."); }
    private async Task<decimal> BalanceValue(SqliteConnection c, SqliteTransaction tx, string w, string p, string? v, CancellationToken ct) { await using var cmd = c.CreateCommand(); cmd.Transaction = tx; cmd.CommandText = "SELECT COALESCE(quantity_available,0) FROM inventory_balances WHERE warehouse_id=$w AND product_id=$p AND (variant_id=$v OR (variant_id IS NULL AND $v IS NULL))"; Add(cmd, "$w", w); Add(cmd, "$p", p); Add(cmd, "$v", (object?)v ?? DBNull.Value); return Convert.ToDecimal(await cmd.ExecuteScalarAsync(ct) ?? 0); }
    private async Task InsertMovement(SqliteConnection c, SqliteTransaction tx, InventoryPost p, InventoryTransactionType type, string? correlation, CancellationToken ct) { await using var cmd = c.CreateCommand(); cmd.Transaction = tx; cmd.CommandText = "INSERT INTO inventory_transactions(id,company_id,branch_id,warehouse_id,product_id,variant_id,transaction_type,quantity,unit_cost,total_cost,reference_no,description,transaction_at,created_at,correlation_id) VALUES($id,$c,$b,$w,$p,$v,$t,$q,$cost,$total,$ref,$desc,$at,$now,$corr)"; Add(cmd, "$id", Guid.NewGuid().ToString()); Add(cmd, "$c", p.CompanyId); Add(cmd, "$b", p.BranchId); Add(cmd, "$w", p.WarehouseId); Add(cmd, "$p", p.ProductId); Add(cmd, "$v", (object?)p.VariantId ?? DBNull.Value); Add(cmd, "$t", type.ToString()); Add(cmd, "$q", p.Quantity); Add(cmd, "$cost", (object?)p.UnitCost ?? DBNull.Value); Add(cmd, "$total", p.UnitCost.HasValue ? p.UnitCost.Value * p.Quantity : DBNull.Value); Add(cmd, "$ref", (object?)p.ReferenceNo ?? DBNull.Value); Add(cmd, "$desc", (object?)p.Description ?? DBNull.Value); Add(cmd, "$at", p.TransactionAt.ToUniversalTime().ToString("O")); Add(cmd, "$now", DateTime.UtcNow.ToString("O")); Add(cmd, "$corr", (object?)correlation ?? DBNull.Value); await cmd.ExecuteNonQueryAsync(ct); }
    private async Task ApplyBalance(SqliteConnection c, SqliteTransaction tx, InventoryPost p, decimal delta, CancellationToken ct)
    {
        await using var exists = c.CreateCommand(); exists.Transaction = tx; exists.CommandText = "SELECT COUNT(*) FROM inventory_balances WHERE warehouse_id=$w AND product_id=$p AND (variant_id=$v OR (variant_id IS NULL AND $v IS NULL))"; Add(exists, "$w", p.WarehouseId); Add(exists, "$p", p.ProductId); Add(exists, "$v", (object?)p.VariantId ?? DBNull.Value); var found = Convert.ToInt64(await exists.ExecuteScalarAsync(ct)) > 0;
        await using var cmd = c.CreateCommand(); cmd.Transaction = tx;
        if (found) cmd.CommandText = "UPDATE inventory_balances SET quantity_on_hand=quantity_on_hand+$d,quantity_available=quantity_available+$d,last_transaction_at=$at,updated_at=$now WHERE warehouse_id=$w AND product_id=$p AND (variant_id=$v OR (variant_id IS NULL AND $v IS NULL))";
        else cmd.CommandText = "INSERT INTO inventory_balances(company_id,branch_id,warehouse_id,product_id,variant_id,quantity_on_hand,quantity_available,last_transaction_at,updated_at) VALUES($c,$b,$w,$p,$v,$d,$d,$at,$now)";
        Add(cmd, "$c", p.CompanyId); Add(cmd, "$b", p.BranchId); Add(cmd, "$w", p.WarehouseId); Add(cmd, "$p", p.ProductId); Add(cmd, "$v", (object?)p.VariantId ?? DBNull.Value); Add(cmd, "$d", delta); Add(cmd, "$at", p.TransactionAt.ToUniversalTime().ToString("O")); Add(cmd, "$now", DateTime.UtcNow.ToString("O")); await cmd.ExecuteNonQueryAsync(ct);
    }
    private static bool IsInbound(string type) => type is "OpeningBalance" or "PurchaseReceipt" or "SaleReturn" or "TransferIn" or "CountIncrease" or "ManualIn";
    private SqliteConnection Open() => new($"Data Source={database.Path};Foreign Keys=True;Default Timeout=5");
    private static void Add(SqliteCommand c, string name, object value) => c.Parameters.AddWithValue(name, value);
}

