using System.Data;
using Microsoft.Data.Sqlite;

namespace R3.Infrastructure;

public sealed record ProductChildEdit(string Id, string Code, string Name, string SizeCode = "", string ColorCode = "", string ModelCode = "", string Barcode = "", string UnitId = "", decimal Quantity = 1, bool IsPrimary = false, bool IsActive = true, string VariantId = "");
public sealed record ProductAggregateEdit(string Id, string CompanyId, string Code, string Name, string BrandId, string CategoryId, string UnitId, string ProductType, decimal VatRate, bool IsActive, IReadOnlyList<ProductChildEdit> Variants, IReadOnlyList<ProductChildEdit> Barcodes, decimal PurchaseVatRate = 0, decimal ExciseRate = 0, decimal MinimumStock = 0, decimal MaximumStock = 0, decimal MinimumOrderQuantity = 0, decimal OrderMultiple = 0, bool IsSellable = true, string ImagePath = "");
public sealed record ProductDetailEdit(ProductAggregateEdit Product, IReadOnlyList<ProductChildEdit> Variants, IReadOnlyList<ProductChildEdit> Barcodes);
public sealed class LocalProductService(StoreDatabase database)
{
    public DataTable Search(string? search = null)
    {
        var q = search?.Trim() ?? ""; return database.Query("""
            SELECT p.id AS Id,p.code AS Kod,p.name AS Ad,COALESCE(b.name,'') AS Marka,COALESCE(c.name,'') AS Kategori,u.name AS Birim,p.vat_rate AS KDV,p.product_type AS ProductType,
            (SELECT COUNT(*) FROM product_variants v WHERE v.product_id=p.id AND v.is_active=1) AS Varyant,
            (SELECT COUNT(*) FROM product_barcodes x WHERE x.product_id=p.id AND x.is_active=1) AS Barkod,p.is_active AS Aktif
            FROM products p JOIN units u ON u.id=p.base_unit_id LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id
            WHERE p.code LIKE $q OR p.name LIKE $q OR EXISTS(SELECT 1 FROM product_barcodes z WHERE z.product_id=p.id AND z.barcode LIKE $q) ORDER BY p.code
            """, ("$q", $"%{q}%"));
    }
    public ProductDetailEdit? GetDetail(string productId, string companyId)
    {
        using var c = new SqliteConnection($"Data Source={database.Path};Foreign Keys=True;Default Timeout=5"); c.Open();
        using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT id,company_id,code,name,COALESCE(brand_id,''),COALESCE(category_id,''),base_unit_id,product_type,vat_rate,is_active,purchase_vat_rate,excise_rate,minimum_stock,maximum_stock,minimum_order_quantity,order_multiple,is_sellable,COALESCE(image_path,'') FROM products WHERE id=$id AND company_id=$company"; cmd.Parameters.AddWithValue("$id", productId); cmd.Parameters.AddWithValue("$company", companyId);
        using var r = cmd.ExecuteReader(); if (!r.Read()) return null;
        var product = new ProductAggregateEdit(r.GetString(0), r.GetString(1), r.GetString(2), r.GetString(3), r.GetString(4), r.GetString(5), r.GetString(6), r.GetString(7), r.GetDecimal(8), r.GetBoolean(9), [], [], r.GetDecimal(10), r.GetDecimal(11), r.GetDecimal(12), r.GetDecimal(13), r.GetDecimal(14), r.GetDecimal(15), r.GetBoolean(16), r.GetString(17));
        var variants = new List<ProductChildEdit>(); var barcodes = new List<ProductChildEdit>();
        using var v = c.CreateCommand(); v.CommandText = "SELECT id,code,name,COALESCE(size_code,''),COALESCE(color_code,''),COALESCE(model_code,''),is_active FROM product_variants WHERE product_id=$p ORDER BY code"; v.Parameters.AddWithValue("$p", productId); using var vr = v.ExecuteReader(); while (vr.Read()) variants.Add(new ProductChildEdit(vr.GetString(0), vr.GetString(1), vr.GetString(2), vr.GetString(3), vr.GetString(4), vr.GetString(5), IsActive: vr.GetBoolean(6)));
        using var b = c.CreateCommand(); b.CommandText = "SELECT id,COALESCE(variant_id,''),COALESCE(unit_id,''),barcode,quantity,is_primary,is_active FROM product_barcodes WHERE product_id=$p ORDER BY barcode"; b.Parameters.AddWithValue("$p", productId); using var br = b.ExecuteReader(); while (br.Read()) barcodes.Add(new ProductChildEdit(br.GetString(0), "", "", Barcode: br.GetString(3), UnitId: br.GetString(2), Quantity: br.GetDecimal(4), IsPrimary: br.GetBoolean(5), IsActive: br.GetBoolean(6), VariantId: br.GetString(1)));
        return new ProductDetailEdit(product with { Variants = variants, Barcodes = barcodes }, variants, barcodes);
    }
    public void Save(ProductAggregateEdit edit)
    {
        if (string.IsNullOrWhiteSpace(edit.CompanyId) || string.IsNullOrWhiteSpace(edit.Code) || string.IsNullOrWhiteSpace(edit.Name) || string.IsNullOrWhiteSpace(edit.UnitId)) throw new ArgumentException("Firma, kod, ad ve temel birim zorunludur.");
        if (edit.VatRate is < 0 or > 100) throw new ArgumentException("KDV 0 ile 100 arasında olmalıdır.");
        var id = string.IsNullOrWhiteSpace(edit.Id) ? Guid.NewGuid().ToString() : edit.Id; var now = DateTime.UtcNow.ToString("O");
        using var connection = new SqliteConnection($"Data Source={database.Path};Foreign Keys=True;Default Timeout=5"); connection.Open(); using var tx = connection.BeginTransaction();
        using var cmd = connection.CreateCommand(); cmd.Transaction = tx; cmd.CommandText = "SELECT COUNT(*) FROM products WHERE company_id=$company AND code=$code AND id<>$id"; cmd.Parameters.AddWithValue("$company", edit.CompanyId); cmd.Parameters.AddWithValue("$code", edit.Code.Trim().ToUpperInvariant()); cmd.Parameters.AddWithValue("$id", id); if (Convert.ToInt64(cmd.ExecuteScalar()) > 0) throw new ArgumentException("Bu ürün kodu firma içinde zaten kullanılıyor.");
        cmd.Parameters.Clear(); cmd.CommandText = "INSERT INTO products(id,company_id,code,name,brand_id,category_id,base_unit_id,product_type,vat_rate,purchase_vat_rate,excise_rate,minimum_stock,maximum_stock,minimum_order_quantity,order_multiple,is_sellable,is_active,image_path,created_at,updated_at) VALUES($id,$company,$code,$name,$brand,$category,$unit,$type,$vat,$purchaseVat,$excise,$minimumStock,$maximumStock,$minimumOrder,$orderMultiple,$sellable,$active,$image,$now,$now) ON CONFLICT(id) DO UPDATE SET code=$code,name=$name,brand_id=$brand,category_id=$category,base_unit_id=$unit,product_type=$type,vat_rate=$vat,purchase_vat_rate=$purchaseVat,excise_rate=$excise,minimum_stock=$minimumStock,maximum_stock=$maximumStock,minimum_order_quantity=$minimumOrder,order_multiple=$orderMultiple,is_sellable=$sellable,is_active=$active,image_path=$image,updated_at=$now";
        cmd.Parameters.AddWithValue("$id", id); cmd.Parameters.AddWithValue("$company", edit.CompanyId); cmd.Parameters.AddWithValue("$code", edit.Code.Trim().ToUpperInvariant()); cmd.Parameters.AddWithValue("$name", edit.Name.Trim()); cmd.Parameters.AddWithValue("$brand", (object?)NullIf(edit.BrandId) ?? DBNull.Value); cmd.Parameters.AddWithValue("$category", (object?)NullIf(edit.CategoryId) ?? DBNull.Value); cmd.Parameters.AddWithValue("$unit", edit.UnitId); cmd.Parameters.AddWithValue("$type", edit.ProductType); cmd.Parameters.AddWithValue("$vat", edit.VatRate); cmd.Parameters.AddWithValue("$purchaseVat", edit.PurchaseVatRate); cmd.Parameters.AddWithValue("$excise", edit.ExciseRate); cmd.Parameters.AddWithValue("$minimumStock", edit.MinimumStock); cmd.Parameters.AddWithValue("$maximumStock", edit.MaximumStock); cmd.Parameters.AddWithValue("$minimumOrder", edit.MinimumOrderQuantity); cmd.Parameters.AddWithValue("$orderMultiple", edit.OrderMultiple); cmd.Parameters.AddWithValue("$sellable", edit.IsSellable ? 1 : 0); cmd.Parameters.AddWithValue("$active", edit.IsActive ? 1 : 0); cmd.Parameters.AddWithValue("$image", edit.ImagePath?.Trim() ?? ""); cmd.Parameters.AddWithValue("$now", now); cmd.ExecuteNonQuery();
        foreach (var variant in edit.Variants) { if (string.IsNullOrWhiteSpace(variant.Code) || string.IsNullOrWhiteSpace(variant.Name)) throw new ArgumentException("Varyant kodu ve adı zorunludur."); var vid = string.IsNullOrWhiteSpace(variant.Id) ? Guid.NewGuid().ToString() : variant.Id; using var child = connection.CreateCommand(); child.Transaction = tx; child.CommandText = "INSERT INTO product_variants(id,product_id,code,name,size_code,color_code,model_code,is_active) VALUES($id,$product,$code,$name,$size,$color,$model,$active) ON CONFLICT(id) DO UPDATE SET code=$code,name=$name,size_code=$size,color_code=$color,model_code=$model,is_active=$active"; child.Parameters.AddWithValue("$id", vid); child.Parameters.AddWithValue("$product", id); child.Parameters.AddWithValue("$code", variant.Code.Trim().ToUpperInvariant()); child.Parameters.AddWithValue("$name", variant.Name.Trim()); child.Parameters.AddWithValue("$size", (object?)NullIf(variant.SizeCode) ?? DBNull.Value); child.Parameters.AddWithValue("$color", (object?)NullIf(variant.ColorCode) ?? DBNull.Value); child.Parameters.AddWithValue("$model", (object?)NullIf(variant.ModelCode) ?? DBNull.Value); child.Parameters.AddWithValue("$active", variant.IsActive ? 1 : 0); child.ExecuteNonQuery(); }
        foreach (var barcode in edit.Barcodes) { if (string.IsNullOrWhiteSpace(barcode.Barcode) || barcode.Quantity <= 0) throw new ArgumentException("Barkod boş olamaz ve miktar 0'dan büyük olmalıdır."); using var check = connection.CreateCommand(); check.Transaction = tx; check.CommandText = "SELECT COUNT(*) FROM product_barcodes WHERE barcode=$barcode AND product_id<>$product"; check.Parameters.AddWithValue("$barcode", barcode.Barcode.Trim()); check.Parameters.AddWithValue("$product", id); if (Convert.ToInt64(check.ExecuteScalar()) > 0) throw new ArgumentException($"{barcode.Barcode.Trim()} barkodu başka bir üründe kayıtlı."); var bid = string.IsNullOrWhiteSpace(barcode.Id) ? Guid.NewGuid().ToString() : barcode.Id; using var child = connection.CreateCommand(); child.Transaction = tx; child.CommandText = "INSERT INTO product_barcodes(id,product_id,variant_id,unit_id,barcode,quantity,is_primary,is_active) VALUES($id,$product,$variant,$unit,$barcode,$quantity,$primary,$active) ON CONFLICT(id) DO UPDATE SET variant_id=$variant,unit_id=$unit,barcode=$barcode,quantity=$quantity,is_primary=$primary,is_active=$active"; child.Parameters.AddWithValue("$id", bid); child.Parameters.AddWithValue("$product", id); child.Parameters.AddWithValue("$variant", (object?)NullIf(barcode.VariantId) ?? DBNull.Value); child.Parameters.AddWithValue("$unit", (object?)NullIf(barcode.UnitId) ?? DBNull.Value); child.Parameters.AddWithValue("$barcode", barcode.Barcode.Trim()); child.Parameters.AddWithValue("$quantity", barcode.Quantity); child.Parameters.AddWithValue("$primary", barcode.IsPrimary ? 1 : 0); child.Parameters.AddWithValue("$active", barcode.IsActive ? 1 : 0); if (barcode.IsPrimary) { using var clear = connection.CreateCommand(); clear.Transaction = tx; clear.CommandText = "UPDATE product_barcodes SET is_primary=0 WHERE product_id=$product"; clear.Parameters.AddWithValue("$product", id); clear.ExecuteNonQuery(); } child.ExecuteNonQuery(); }
        var variantIds = edit.Variants.Where(x => !string.IsNullOrWhiteSpace(x.Id)).Select(x => x.Id).ToHashSet(StringComparer.OrdinalIgnoreCase);
        using (var existing = connection.CreateCommand()) { existing.Transaction = tx; existing.CommandText = "SELECT id FROM product_variants WHERE product_id=$p"; existing.Parameters.AddWithValue("$p", id); var ids = new List<string>(); using (var rr = existing.ExecuteReader()) while (rr.Read()) ids.Add(rr.GetString(0)); foreach (var childId in ids.Where(x => !variantIds.Contains(x))) using (var off = connection.CreateCommand()) { off.Transaction = tx; off.CommandText = "UPDATE product_variants SET is_active=0 WHERE id=$id"; off.Parameters.AddWithValue("$id", childId); off.ExecuteNonQuery(); } }
        var barcodeIds = edit.Barcodes.Where(x => !string.IsNullOrWhiteSpace(x.Id)).Select(x => x.Id).ToHashSet(StringComparer.OrdinalIgnoreCase);
        using (var existing = connection.CreateCommand()) { existing.Transaction = tx; existing.CommandText = "SELECT id FROM product_barcodes WHERE product_id=$p"; existing.Parameters.AddWithValue("$p", id); var ids = new List<string>(); using (var rr = existing.ExecuteReader()) while (rr.Read()) ids.Add(rr.GetString(0)); foreach (var childId in ids.Where(x => !barcodeIds.Contains(x))) using (var off = connection.CreateCommand()) { off.Transaction = tx; off.CommandText = "UPDATE product_barcodes SET is_active=0 WHERE id=$id"; off.Parameters.AddWithValue("$id", childId); off.ExecuteNonQuery(); } }
        using var audit = connection.CreateCommand(); audit.Transaction = tx; audit.CommandText = "INSERT INTO audit_logs(id,entity_type,entity_id,action,new_values,created_at) VALUES($id,'Product','" + id + "','UPDATE',$new,$now)"; audit.Parameters.AddWithValue("$id", Guid.NewGuid().ToString()); audit.Parameters.AddWithValue("$new", edit.Code); audit.Parameters.AddWithValue("$now", now); audit.ExecuteNonQuery(); tx.Commit();
    }
    private static string? NullIf(string value) => string.IsNullOrWhiteSpace(value) ? null : value.Trim();
}
