using System.Data;
using Microsoft.Data.Sqlite;

namespace R3.Infrastructure;

public sealed record InventoryTransferLineEdit(string ProductId, string UnitId, decimal Quantity, decimal BaseQuantity, string? VariantId = null, string? LotId = null, string? SerialNumber = null, DateTime? ExpiryDate = null, string Description = "");
public sealed record InventoryTransferEdit(string CompanyId, string BranchId, string SourceWarehouseId, string? SourceLocationId, string TargetWarehouseId, string? TargetLocationId, DateTime TransferDate, IReadOnlyList<InventoryTransferLineEdit> Lines, string Description = "");

public sealed class LocalInventoryTransferService(StoreDatabase database)
{
    public string CreateDraft(InventoryTransferEdit edit, string userId)
    {
        ValidateHeader(edit); using var c = database.OpenConnection(); using var tx = c.BeginTransaction(); ValidateWarehouses(c, tx, edit); foreach (var line in edit.Lines) ValidateLine(c, tx, edit.CompanyId, line);
        var id = Guid.NewGuid().ToString(); var now = DateTime.UtcNow.ToString("O"); var number = NextNumber(c, tx, edit.CompanyId, edit.TransferDate.Year);
        using (var cmd = c.CreateCommand()) { cmd.Transaction = tx; cmd.CommandText = "INSERT INTO transfer_documents(id,company_id,branch_id,transfer_no,transfer_date,source_warehouse_id,source_location_id,target_warehouse_id,target_location_id,status,description,requested_by,created_at) VALUES($id,$company,$branch,$no,$date,$sw,$sl,$tw,$tl,'Draft',$description,$user,$now)"; Add(cmd,"$id",id); Add(cmd,"$company",edit.CompanyId); Add(cmd,"$branch",edit.BranchId); Add(cmd,"$no",number); Add(cmd,"$date",edit.TransferDate.ToUniversalTime().ToString("O")); Add(cmd,"$sw",edit.SourceWarehouseId); Add(cmd,"$sl",(object?)edit.SourceLocationId??DBNull.Value); Add(cmd,"$tw",edit.TargetWarehouseId); Add(cmd,"$tl",(object?)edit.TargetLocationId??DBNull.Value); Add(cmd,"$description",edit.Description); Add(cmd,"$user",userId); Add(cmd,"$now",now); cmd.ExecuteNonQuery(); }
        var no = 1; foreach (var line in edit.Lines) { using var cmd=c.CreateCommand(); cmd.Transaction=tx; cmd.CommandText="INSERT INTO transfer_document_lines(id,transfer_document_id,line_no,product_id,variant_id,unit_id,quantity,base_quantity,lot_id,serial_number,expiry_date,description) VALUES($id,$doc,$no,$product,$variant,$unit,$quantity,$base,$lot,$serial,$expiry,$description)"; Add(cmd,"$id",Guid.NewGuid().ToString()); Add(cmd,"$doc",id); Add(cmd,"$no",no++); Add(cmd,"$product",line.ProductId); Add(cmd,"$variant",(object?)line.VariantId??DBNull.Value); Add(cmd,"$unit",line.UnitId); Add(cmd,"$quantity",line.Quantity); Add(cmd,"$base",line.BaseQuantity); Add(cmd,"$lot",(object?)line.LotId??DBNull.Value); Add(cmd,"$serial",(object?)line.SerialNumber??DBNull.Value); Add(cmd,"$expiry",line.ExpiryDate?.ToUniversalTime().ToString("O")??(object)DBNull.Value); Add(cmd,"$description",line.Description); cmd.ExecuteNonQuery(); }
        Audit(c,tx,edit.CompanyId,id,userId,"TransferDraftCreated",$"transferNo={number}"); tx.Commit(); return id;
    }

    public async Task<string> ApproveAsync(string transferId, string userId, CancellationToken ct = default)
    {
        await using var c=database.OpenConnection(); await using var tx=c.BeginTransaction(); var doc=ReadDocument(c,tx,transferId) ?? throw new InvalidOperationException("Transfer fişi bulunamadı."); if(doc.Status!="Draft") throw new InvalidOperationException("Sadece taslak transfer onaylanabilir."); InventoryAccessGuard.Ensure(database,c,tx,doc.SourceWarehouseId); InventoryAccessGuard.Ensure(database,c,tx,doc.TargetWarehouseId); var lines=ReadLines(c,tx,transferId); if(lines.Count==0) throw new InvalidOperationException("Transfer fişinde en az bir satır olmalıdır."); var correlation=Guid.NewGuid().ToString();
        foreach(var line in lines) { ValidateProduct(c,tx,doc.CompanyId,line.ProductId); var available=Balance(c,tx,doc.SourceWarehouseId,doc.SourceLocationId,line.ProductId,line.VariantId); InventoryStockPolicy.EnsureAvailable(c,tx,doc.SourceWarehouseId,available,line.BaseQuantity,$"Yetersiz stok. Ürün: {line.ProductId}; mevcut: {available:N2}; talep edilen: {line.BaseQuantity:N2}."); }
        foreach(var line in lines) { await Movement(c,tx,doc,line,"TransferOut",correlation,userId,ct); await Apply(c,tx,doc.SourceWarehouseId,doc.SourceLocationId,doc.CompanyId,doc.BranchId,line,-line.BaseQuantity,ct); await Movement(c,tx,doc,line,"TransferIn",correlation,userId,ct); await Apply(c,tx,doc.TargetWarehouseId,doc.TargetLocationId,doc.CompanyId,doc.BranchId,line,line.BaseQuantity,ct); }
        await using(var cmd=c.CreateCommand()){cmd.Transaction=tx;cmd.CommandText="UPDATE transfer_documents SET status='Approved',approved_by=$user,approved_at=$now,correlation_id=$correlation WHERE id=$id AND status='Draft'";Add(cmd,"$user",userId);Add(cmd,"$now",DateTime.UtcNow.ToString("O"));Add(cmd,"$correlation",correlation);Add(cmd,"$id",transferId);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Transfer başka bir işlem tarafından onaylandı.");} Audit(c,tx,doc.CompanyId,transferId,userId,"TransferApproved",$"correlationId={correlation}"); await tx.CommitAsync(ct); return doc.TransferNo;
    }

    public DataTable Search(string companyId, string? status=null) => database.Query("SELECT t.id AS Id,t.transfer_no AS TransferNo,t.transfer_date AS Tarih,COALESCE(sw.name,t.source_warehouse_id) AS KaynakDepo,COALESCE(sl.code,'') AS KaynakLokasyon,COALESCE(tw.name,t.target_warehouse_id) AS HedefDepo,COALESCE(tl.code,'') AS HedefLokasyon,t.status AS Durum,COUNT(l.id) AS SatirSayisi,COALESCE(SUM(l.base_quantity),0) AS TemelMiktar,t.requested_by AS Olusturan,t.approved_by AS Onaylayan FROM transfer_documents t LEFT JOIN transfer_document_lines l ON l.transfer_document_id=t.id LEFT JOIN warehouses sw ON sw.id=t.source_warehouse_id LEFT JOIN warehouses tw ON tw.id=t.target_warehouse_id LEFT JOIN warehouse_locations sl ON sl.id=t.source_location_id LEFT JOIN warehouse_locations tl ON tl.id=t.target_location_id WHERE t.company_id=$company AND ($status='' OR t.status=$status) GROUP BY t.id ORDER BY t.transfer_date DESC,t.created_at DESC", ("$company",companyId),("$status",status??""));

    private static void ValidateHeader(InventoryTransferEdit e){if(string.IsNullOrWhiteSpace(e.CompanyId)||string.IsNullOrWhiteSpace(e.BranchId))throw new ArgumentException("Firma ve şube zorunludur.");if(string.IsNullOrWhiteSpace(e.SourceWarehouseId)||string.IsNullOrWhiteSpace(e.TargetWarehouseId))throw new ArgumentException("Kaynak ve hedef depo zorunludur.");if(e.SourceWarehouseId==e.TargetWarehouseId&&e.SourceLocationId==e.TargetLocationId)throw new ArgumentException("Kaynak ve hedef depo/lokasyon aynı olamaz.");if(e.Lines is null||e.Lines.Count==0)throw new ArgumentException("Transfer fişinde en az bir satır olmalıdır.");}
    private static void ValidateWarehouses(SqliteConnection c,SqliteTransaction tx,InventoryTransferEdit e){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="SELECT COUNT(*) FROM warehouses WHERE id=$id AND company_id=$company AND branch_id=$branch AND is_active=1";Add(cmd,"$company",e.CompanyId);Add(cmd,"$branch",e.BranchId);Add(cmd,"$id",e.SourceWarehouseId);if(Convert.ToInt32(cmd.ExecuteScalar())!=1)throw new ArgumentException("Kaynak depo aktif değil veya şubeye ait değil.");cmd.Parameters["$id"].Value=e.TargetWarehouseId;if(Convert.ToInt32(cmd.ExecuteScalar())!=1)throw new ArgumentException("Hedef depo aktif değil veya şubeye ait değil.");ValidateLocation(c,tx,e.SourceWarehouseId,e.SourceLocationId);ValidateLocation(c,tx,e.TargetWarehouseId,e.TargetLocationId);}
    private static void ValidateLocation(SqliteConnection c,SqliteTransaction tx,string warehouse,string? location){using var req=c.CreateCommand();req.Transaction=tx;req.CommandText="SELECT requires_location FROM warehouses WHERE id=$id";Add(req,"$id",warehouse);if(Convert.ToInt32(req.ExecuteScalar()??0)==1&&string.IsNullOrWhiteSpace(location))throw new ArgumentException("Lokasyon zorunlu olan depoda lokasyon seçilmelidir.");if(string.IsNullOrWhiteSpace(location))return;using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="SELECT COUNT(*) FROM warehouse_locations WHERE id=$location AND warehouse_id=$warehouse AND is_active=1";Add(cmd,"$location",location);Add(cmd,"$warehouse",warehouse);if(Convert.ToInt32(cmd.ExecuteScalar())!=1)throw new ArgumentException("Lokasyon seçilen depoya ait değil veya pasif.");}
    private static void ValidateLine(SqliteConnection c,SqliteTransaction tx,string company,InventoryTransferLineEdit l){if(string.IsNullOrWhiteSpace(l.ProductId)||string.IsNullOrWhiteSpace(l.UnitId)||l.Quantity<=0||l.BaseQuantity<=0)throw new ArgumentException("Transfer satırında ürün, birim ve pozitif miktar zorunludur.");ValidateProduct(c,tx,company,l.ProductId);}
    private static void ValidateProduct(SqliteConnection c,SqliteTransaction tx,string company,string product){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="SELECT product_type,is_active FROM products WHERE id=$id AND company_id=$company";Add(cmd,"$id",product);Add(cmd,"$company",company);using var r=cmd.ExecuteReader();if(!r.Read()||!r.GetBoolean(1)||r.GetString(0)!="Stock")throw new ArgumentException("Pasif veya stok tipi olmayan ürün transfer edilemez.");}
    private static string NextNumber(SqliteConnection c,SqliteTransaction tx,string company,int year){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="SELECT COALESCE(MAX(CAST(SUBSTR(transfer_no,10) AS INTEGER)),0)+1 FROM transfer_documents WHERE company_id=$company AND transfer_no LIKE $prefix || '%'";Add(cmd,"$company",company);Add(cmd,"$prefix",$"TR-{year}-");return $"TR-{year}-"+Convert.ToInt32(cmd.ExecuteScalar()).ToString("D6");}
    private static (string Id,string CompanyId,string BranchId,string TransferNo,string SourceWarehouseId,string? SourceLocationId,string TargetWarehouseId,string? TargetLocationId,string Status)? ReadDocument(SqliteConnection c,SqliteTransaction tx,string id){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="SELECT id,company_id,branch_id,transfer_no,source_warehouse_id,source_location_id,target_warehouse_id,target_location_id,status FROM transfer_documents WHERE id=$id";Add(cmd,"$id",id);using var r=cmd.ExecuteReader();if(!r.Read())return null;return(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.GetString(6),r.IsDBNull(7)?null:r.GetString(7),r.GetString(8));}
    private static List<(string ProductId,string? VariantId,decimal BaseQuantity,string? LotId,string? SerialNumber)> ReadLines(SqliteConnection c,SqliteTransaction tx,string id){var list=new List<(string,string?,decimal,string?,string?)>();using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="SELECT product_id,variant_id,base_quantity,lot_id,serial_number FROM transfer_document_lines WHERE transfer_document_id=$id ORDER BY line_no";Add(cmd,"$id",id);using var r=cmd.ExecuteReader();while(r.Read())list.Add((r.GetString(0),r.IsDBNull(1)?null:r.GetString(1),r.GetDecimal(2),r.IsDBNull(3)?null:r.GetString(3),r.IsDBNull(4)?null:r.GetString(4)));return list;}
    private static decimal Balance(SqliteConnection c,SqliteTransaction tx,string warehouse,string? location,string product,string? variant){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText=string.IsNullOrWhiteSpace(location)?"SELECT COALESCE(quantity_available,0) FROM inventory_balances WHERE warehouse_id=$w AND product_id=$p AND (variant_id=$v OR (variant_id IS NULL AND $v IS NULL))":"SELECT COALESCE(quantity_available,0) FROM warehouse_location_balances WHERE warehouse_id=$w AND location_id=$l AND product_id=$p AND (variant_id=$v OR (variant_id IS NULL AND $v IS NULL))";Add(cmd,"$w",warehouse);Add(cmd,"$l",(object?)location??DBNull.Value);Add(cmd,"$p",product);Add(cmd,"$v",(object?)variant??DBNull.Value);return Convert.ToDecimal(cmd.ExecuteScalar()??0);}
    private static async Task Movement(SqliteConnection c,SqliteTransaction tx,(string Id,string CompanyId,string BranchId,string TransferNo,string SourceWarehouseId,string? SourceLocationId,string TargetWarehouseId,string? TargetLocationId,string Status) d,(string ProductId,string? VariantId,decimal BaseQuantity,string? LotId,string? SerialNumber) l,string type,string correlation,string user,CancellationToken ct){await using var cmd=c.CreateCommand();cmd.Transaction=tx;var warehouse=type=="TransferOut"?d.SourceWarehouseId:d.TargetWarehouseId;var location=type=="TransferOut"?d.SourceLocationId:d.TargetLocationId;cmd.CommandText="INSERT INTO inventory_transactions(id,company_id,branch_id,warehouse_id,location_id,product_id,variant_id,transaction_type,quantity,base_quantity,lot_id,serial_number,document_type,document_id,reference_no,transaction_at,created_by,created_at,correlation_id) VALUES($id,$company,$branch,$warehouse,$location,$product,$variant,$type,$quantity,$base,$lot,$serial,'InventoryTransfer',$document,$number,$now,$user,$now,$correlation)";Add(cmd,"$id",Guid.NewGuid().ToString());Add(cmd,"$company",d.CompanyId);Add(cmd,"$branch",d.BranchId);Add(cmd,"$warehouse",warehouse);Add(cmd,"$location",(object?)location??DBNull.Value);Add(cmd,"$product",l.ProductId);Add(cmd,"$variant",(object?)l.VariantId??DBNull.Value);Add(cmd,"$type",type);Add(cmd,"$quantity",l.BaseQuantity);Add(cmd,"$base",l.BaseQuantity);Add(cmd,"$lot",(object?)l.LotId??DBNull.Value);Add(cmd,"$serial",(object?)l.SerialNumber??DBNull.Value);Add(cmd,"$document",d.Id);Add(cmd,"$number",d.TransferNo);Add(cmd,"$now",DateTime.UtcNow.ToString("O"));Add(cmd,"$user",user);Add(cmd,"$correlation",correlation);await cmd.ExecuteNonQueryAsync(ct);}
    private static async Task Apply(SqliteConnection c,SqliteTransaction tx,string warehouse,string? location,string company,string branch,(string ProductId,string? VariantId,decimal BaseQuantity,string? LotId,string? SerialNumber) l,decimal delta,CancellationToken ct){await using var exists=c.CreateCommand();exists.Transaction=tx;exists.CommandText="SELECT COUNT(*) FROM inventory_balances WHERE warehouse_id=$w AND product_id=$p AND (variant_id=$v OR (variant_id IS NULL AND $v IS NULL))";Add(exists,"$w",warehouse);Add(exists,"$p",l.ProductId);Add(exists,"$v",(object?)l.VariantId??DBNull.Value);var found=Convert.ToInt32(await exists.ExecuteScalarAsync(ct))>0;await using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText=found?"UPDATE inventory_balances SET quantity_on_hand=quantity_on_hand+$d,quantity_available=quantity_available+$d,updated_at=$now WHERE warehouse_id=$w AND product_id=$p AND (variant_id=$v OR (variant_id IS NULL AND $v IS NULL))":"INSERT INTO inventory_balances(company_id,branch_id,warehouse_id,product_id,variant_id,quantity_on_hand,quantity_available,updated_at) VALUES($c,$b,$w,$p,$v,$d,$d,$now)";Add(cmd,"$c",company);Add(cmd,"$b",branch);Add(cmd,"$w",warehouse);Add(cmd,"$p",l.ProductId);Add(cmd,"$v",(object?)l.VariantId??DBNull.Value);Add(cmd,"$d",delta);Add(cmd,"$now",DateTime.UtcNow.ToString("O"));await cmd.ExecuteNonQueryAsync(ct);if(string.IsNullOrWhiteSpace(location))return;await using var locExists=c.CreateCommand();locExists.Transaction=tx;locExists.CommandText="SELECT COUNT(*) FROM warehouse_location_balances WHERE warehouse_id=$w AND location_id=$l AND product_id=$p AND (variant_id=$v OR (variant_id IS NULL AND $v IS NULL))";Add(locExists,"$w",warehouse);Add(locExists,"$l",location);Add(locExists,"$p",l.ProductId);Add(locExists,"$v",(object?)l.VariantId??DBNull.Value);var locFound=Convert.ToInt32(await locExists.ExecuteScalarAsync(ct))>0;await using var loc=c.CreateCommand();loc.Transaction=tx;loc.CommandText=locFound?"UPDATE warehouse_location_balances SET quantity_on_hand=quantity_on_hand+$d,quantity_available=quantity_available+$d,updated_at=$now WHERE warehouse_id=$w AND location_id=$l AND product_id=$p AND (variant_id=$v OR (variant_id IS NULL AND $v IS NULL))":"INSERT INTO warehouse_location_balances(id,warehouse_id,location_id,product_id,variant_id,quantity_on_hand,quantity_available,updated_at) VALUES($id,$w,$l,$p,$v,$d,$d,$now)";Add(loc,"$id",Guid.NewGuid().ToString());Add(loc,"$w",warehouse);Add(loc,"$l",location);Add(loc,"$p",l.ProductId);Add(loc,"$v",(object?)l.VariantId??DBNull.Value);Add(loc,"$d",delta);Add(loc,"$now",DateTime.UtcNow.ToString("O"));await loc.ExecuteNonQueryAsync(ct);}
    private static void Audit(SqliteConnection c,SqliteTransaction tx,string company,string entity,string user,string action,string values){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="INSERT INTO audit_logs(id,user_id,company_id,entity_type,entity_id,action,new_values,created_at) VALUES($id,$user,$company,'InventoryTransfer',$entity,$action,$values,$now)";Add(cmd,"$id",Guid.NewGuid().ToString());Add(cmd,"$user",user);Add(cmd,"$company",company);Add(cmd,"$entity",entity);Add(cmd,"$action",action);Add(cmd,"$values",values);Add(cmd,"$now",DateTime.UtcNow.ToString("O"));cmd.ExecuteNonQuery();}
    private static void Add(SqliteCommand c,string n,object v)=>c.Parameters.AddWithValue(n,v);
}
