using System.Data;
using Microsoft.Data.Sqlite;

namespace R3.Infrastructure;

public sealed record SalesLineEdit(string ProductId, string? VariantId, string UnitId, string? BarcodeId, decimal Quantity, decimal QuantityFactor, decimal UnitPrice, decimal DiscountRate, decimal VatRate, string Description = "");
public sealed record SalesDraftEdit(string Id, string CompanyId, string BranchId, string WarehouseId, string AccountId, DateTime DocumentDate, string Description, IReadOnlyList<SalesLineEdit> Lines);
public sealed record SalesTotals(decimal Subtotal, decimal DiscountTotal, decimal TaxTotal, decimal GrandTotal);
public sealed class LocalSalesService(StoreDatabase database)
{
    public DataTable Search(string companyId, string? search = null, string? status = null) => database.Query("SELECT s.id AS Id,COALESCE(s.document_no,'Taslak') AS FaturaNo,s.document_date AS Tarih,a.code AS CariKod,a.name AS Cari,COALESCE(br.name,s.branch_id) AS Sube,COALESCE(w.name,s.warehouse_id) AS Depo,s.subtotal AS AraToplam,s.discount_total AS Iskonto,s.tax_total AS KDV,s.grand_total AS GenelToplam,s.status AS Durum FROM sales_documents s JOIN accounts a ON a.id=s.account_id LEFT JOIN branches br ON br.id=s.branch_id LEFT JOIN warehouses w ON w.id=s.warehouse_id WHERE s.company_id=$c AND ($q='' OR s.document_no LIKE $q OR a.code LIKE $q OR a.name LIKE $q) AND ($status='' OR s.status=$status) ORDER BY s.document_date DESC", ("$c", companyId), ("$q", $"%{search?.Trim() ?? ""}%"), ("$status", status ?? ""));
    public string CreateDraft(SalesDraftEdit draft) { var id = string.IsNullOrWhiteSpace(draft.Id) ? Guid.NewGuid().ToString() : draft.Id; SaveDraft(draft with { Id = id }); return id; }
    public void SaveDraft(SalesDraftEdit draft)
    {
        if (draft.Lines.Count == 0) throw new ArgumentException("Faturada en az bir satır olmalıdır.");
        using var c = Open(); c.Open(); using var tx = c.BeginTransaction(); var totals = Calculate(draft.Lines); var id = string.IsNullOrWhiteSpace(draft.Id) ? Guid.NewGuid().ToString() : draft.Id;
        using var cmd = c.CreateCommand(); cmd.Transaction = tx; cmd.CommandText = "INSERT INTO sales_documents(id,company_id,branch_id,warehouse_id,account_id,document_date,status,subtotal,discount_total,tax_total,grand_total,description,created_at,updated_at) VALUES($id,$c,$b,$w,$a,$date,'Draft',$sub,$disc,$tax,$total,$desc,$now,$now) ON CONFLICT(id) DO UPDATE SET account_id=$a,warehouse_id=$w,document_date=$date,subtotal=$sub,discount_total=$disc,tax_total=$tax,grand_total=$total,description=$desc,updated_at=$now WHERE sales_documents.status='Draft'";
        Add(cmd,"$id",id); Add(cmd,"$c",draft.CompanyId); Add(cmd,"$b",draft.BranchId); Add(cmd,"$w",draft.WarehouseId); Add(cmd,"$a",draft.AccountId); Add(cmd,"$date",draft.DocumentDate.ToString("O")); Add(cmd,"$sub",totals.Subtotal); Add(cmd,"$disc",totals.DiscountTotal); Add(cmd,"$tax",totals.TaxTotal); Add(cmd,"$total",totals.GrandTotal); Add(cmd,"$desc",draft.Description ?? ""); Add(cmd,"$now",DateTime.UtcNow.ToString("O")); cmd.ExecuteNonQuery();
        using (var del=c.CreateCommand()) { del.Transaction=tx; del.CommandText="DELETE FROM sales_document_lines WHERE sales_document_id=$id"; Add(del,"$id",id); del.ExecuteNonQuery(); }
        var n=1; foreach(var line in draft.Lines) { var calc=CalculateLine(line); using var l=c.CreateCommand(); l.Transaction=tx; l.CommandText="INSERT INTO sales_document_lines(id,sales_document_id,line_no,product_id,variant_id,unit_id,barcode_id,quantity,quantity_factor,base_quantity,unit_price,discount_rate,discount_amount,vat_rate,gross_amount,net_amount,vat_amount,line_total,description) VALUES($id,$doc,$no,$p,$v,$u,$bar,$q,$f,$base,$price,$dr,$da,$vr,$gross,$net,$vat,$total,$desc)"; Add(l,"$id",Guid.NewGuid().ToString()); Add(l,"$doc",id); Add(l,"$no",n++); Add(l,"$p",line.ProductId); Add(l,"$v",(object?)line.VariantId??DBNull.Value); Add(l,"$u",line.UnitId); Add(l,"$bar",(object?)line.BarcodeId??DBNull.Value); Add(l,"$q",line.Quantity); Add(l,"$f",line.QuantityFactor); Add(l,"$base",line.Quantity*line.QuantityFactor); Add(l,"$price",line.UnitPrice); Add(l,"$dr",line.DiscountRate); Add(l,"$da",calc.Discount); Add(l,"$vr",line.VatRate); Add(l,"$gross",calc.Gross); Add(l,"$net",calc.Net); Add(l,"$vat",calc.Vat); Add(l,"$total",calc.Total); Add(l,"$desc",line.Description??""); l.ExecuteNonQuery(); }
        tx.Commit();
    }
    public void Post(string documentId)
    {
        using var c=Open(); c.Open(); using var tx=c.BeginTransaction();
        var doc=ReadDoc(c,tx,documentId); if(doc.Status!="Draft") throw new InvalidOperationException("Fatura daha önce işlenmiş.");
        using var account=c.CreateCommand(); account.Transaction=tx; account.CommandText="SELECT account_type,is_active FROM accounts WHERE id=$id AND company_id=$c"; Add(account,"$id",doc.AccountId); Add(account,"$c",doc.CompanyId); using var ar=account.ExecuteReader(); if(!ar.Read()) throw new InvalidOperationException("Cari hesap bulunamadı."); if(!ar.GetBoolean(1)) throw new InvalidOperationException("Cari hesap pasif."); if(ar.GetString(0) is not ("Customer" or "CustomerAndSupplier")) throw new InvalidOperationException("Satış için müşteri cari hesabı seçilmelidir.");
        using var lines=c.CreateCommand(); lines.Transaction=tx; lines.CommandText="SELECT id,product_id,variant_id,quantity,quantity_factor FROM sales_document_lines WHERE sales_document_id=$id ORDER BY line_no"; Add(lines,"$id",documentId); using var lr=lines.ExecuteReader(); var rows=new List<(string id,string p,string? v,decimal q,decimal f)>(); while(lr.Read()) rows.Add((lr.GetString(0),lr.GetString(1),lr.IsDBNull(2)?null:lr.GetString(2),lr.GetDecimal(3),lr.GetDecimal(4))); lr.Close();
        foreach(var line in rows) { using var p=c.CreateCommand(); p.Transaction=tx; p.CommandText="SELECT product_type,is_active,company_id FROM products WHERE id=$id"; Add(p,"$id",line.p); using var pr=p.ExecuteReader(); if(!pr.Read()||pr.GetString(2)!=doc.CompanyId||!pr.GetBoolean(1)) throw new InvalidOperationException("Ürün pasif veya firma kapsamında değil."); var type=pr.GetString(0); pr.Close(); if(type.Equals("Service",StringComparison.OrdinalIgnoreCase)) continue; var qty=line.q*line.f; using var bal=c.CreateCommand(); bal.Transaction=tx; bal.CommandText="SELECT COALESCE(quantity_available,0) FROM inventory_balances WHERE warehouse_id=$w AND product_id=$p AND (variant_id=$v OR (variant_id IS NULL AND $v IS NULL))"; Add(bal,"$w",doc.WarehouseId); Add(bal,"$p",line.p); Add(bal,"$v",(object?)line.v??DBNull.Value); if(Convert.ToDecimal(bal.ExecuteScalar()??0)<qty) throw new InvalidOperationException("Yetersiz stok."); InsertIssue(c,tx,doc,line.id,qty); ApplyBalance(c,tx,doc,line.v,line.p,-qty); }
        var no=AllocateNumber(c,tx,doc.CompanyId,doc.DocumentDate.Year); using(var up=c.CreateCommand()){up.Transaction=tx;up.CommandText="UPDATE sales_documents SET status='Posted',document_no=$no,posting_date=$date,posted_at=$date,updated_at=$date WHERE id=$id";Add(up,"$no",no);Add(up,"$date",DateTime.UtcNow.ToString("O"));Add(up,"$id",documentId);up.ExecuteNonQuery();}
        using(var at=c.CreateCommand()){at.Transaction=tx;at.CommandText="INSERT INTO account_transactions(id,company_id,branch_id,account_id,transaction_type,debit,document_type,document_id,document_no,description,transaction_at,created_at) VALUES($id,$c,$b,$a,'SalesInvoice',$debit,'SalesInvoice',$doc,$no,$desc,$at,$at)";Add(at,"$id",Guid.NewGuid().ToString());Add(at,"$c",doc.CompanyId);Add(at,"$b",doc.BranchId);Add(at,"$a",doc.AccountId);Add(at,"$debit",doc.GrandTotal);Add(at,"$doc",documentId);Add(at,"$no",no);Add(at,"$desc",doc.Description);Add(at,"$at",DateTime.UtcNow.ToString("O"));at.ExecuteNonQuery();}
        using(var ab=c.CreateCommand()){ab.Transaction=tx;ab.CommandText="INSERT INTO account_balances(company_id,account_id,debit,credit,balance,updated_at) VALUES($c,$a,$d,0,$d,$now) ON CONFLICT(company_id,account_id) DO UPDATE SET debit=debit+$d,balance=balance+$d,updated_at=$now";Add(ab,"$c",doc.CompanyId);Add(ab,"$a",doc.AccountId);Add(ab,"$d",doc.GrandTotal);Add(ab,"$now",DateTime.UtcNow.ToString("O"));ab.ExecuteNonQuery();}
        using(var audit=c.CreateCommand()){audit.Transaction=tx; audit.CommandText="INSERT INTO audit_logs(id,company_id,entity_type,entity_id,action,new_values,created_at) VALUES($id,$c,'SalesDocument',$doc,'SalesInvoicePosted',$values,$now)"; Add(audit,"$id",Guid.NewGuid().ToString()); Add(audit,"$c",doc.CompanyId); Add(audit,"$doc",doc.Id); Add(audit,"$values",$"documentNo={no};accountId={doc.AccountId};grandTotal={doc.GrandTotal};warehouseId={doc.WarehouseId}"); Add(audit,"$now",DateTime.UtcNow.ToString("O")); audit.ExecuteNonQuery();} tx.Commit();
    }
    private static SalesTotals Calculate(IReadOnlyList<SalesLineEdit> lines){var x=lines.Select(CalculateLine).ToList();return new(x.Sum(a=>a.Gross),x.Sum(a=>a.Discount),x.Sum(a=>a.Vat),x.Sum(a=>a.Total));}
    private static (decimal Gross,decimal Discount,decimal Net,decimal Vat,decimal Total) CalculateLine(SalesLineEdit l){if(l.Quantity<=0||l.UnitPrice<0)throw new ArgumentException("Geçerli miktar ve fiyat girin.");var g=l.Quantity*l.UnitPrice;var d=g*l.DiscountRate/100;var n=g-d;var v=n*l.VatRate/100;return(g,d,n,v,n+v);}
    private sealed record Doc(string Id,string CompanyId,string BranchId,string WarehouseId,string AccountId,string Status,decimal GrandTotal,DateTime DocumentDate,string Description);
    private static Doc ReadDoc(SqliteConnection c,SqliteTransaction tx,string id){using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="SELECT id,company_id,branch_id,warehouse_id,account_id,status,grand_total,document_date,description FROM sales_documents WHERE id=$id";Add(q,"$id",id);using var r=q.ExecuteReader();if(!r.Read())throw new KeyNotFoundException("Fatura bulunamadı.");return new(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetDecimal(6),DateTime.Parse(r.GetString(7)),r.GetString(8));}
    private static void InsertIssue(SqliteConnection c,SqliteTransaction tx,Doc d,string line,decimal q){using var x=c.CreateCommand();x.Transaction=tx;x.CommandText="INSERT INTO inventory_transactions(id,company_id,branch_id,warehouse_id,product_id,variant_id,transaction_type,quantity,document_type,document_id,document_line_id,reference_no,description,transaction_at,created_at) SELECT $id,$c,$b,$w,l.product_id,l.variant_id,'SaleIssue',$q,'SalesInvoice',$doc,$line,s.document_no,s.description,$at,$at FROM sales_document_lines l JOIN sales_documents s ON s.id=l.sales_document_id WHERE l.id=$line";Add(x,"$id",Guid.NewGuid().ToString());Add(x,"$c",d.CompanyId);Add(x,"$b",d.BranchId);Add(x,"$w",d.WarehouseId);Add(x,"$q",q);Add(x,"$doc",d.Id);Add(x,"$line",line);Add(x,"$at",DateTime.UtcNow.ToString("O"));x.ExecuteNonQuery();}
    private static void ApplyBalance(SqliteConnection c,SqliteTransaction tx,Doc d,string? v,string p,decimal delta){using var x=c.CreateCommand();x.Transaction=tx;x.CommandText="UPDATE inventory_balances SET quantity_on_hand=quantity_on_hand+$d,quantity_available=quantity_available+$d,updated_at=$now WHERE warehouse_id=$w AND product_id=$p AND (variant_id=$v OR (variant_id IS NULL AND $v IS NULL))";Add(x,"$d",delta);Add(x,"$now",DateTime.UtcNow.ToString("O"));Add(x,"$w",d.WarehouseId);Add(x,"$p",p);Add(x,"$v",(object?)v??DBNull.Value);x.ExecuteNonQuery();}
    private static string AllocateNumber(SqliteConnection c,SqliteTransaction tx,string company,int year){using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO number_sequences(company_id,sequence_type,year,prefix,last_number) VALUES($c,'SalesInvoice',$y,'SF',$n) ON CONFLICT(company_id,sequence_type,year) DO UPDATE SET last_number=last_number+1 RETURNING prefix,last_number";Add(q,"$c",company);Add(q,"$y",year);Add(q,"$n",1);using var r=q.ExecuteReader();r.Read();return $"{r.GetString(0)}-{year}-{r.GetInt32(1):D6}";}
    private SqliteConnection Open()=>new($"Data Source={database.Path};Foreign Keys=True;Default Timeout=5"); private static void Add(SqliteCommand c,string n,object v)=>c.Parameters.AddWithValue(n,v);
}
