using System.Data;
using Microsoft.Data.Sqlite;

namespace R3.Infrastructure;

public sealed record WarehouseEdit(string Id, string CompanyId, string BranchId, string Code, string Name, string WarehouseType = "Main", string Address = "", string? ResponsibleUserId = null, string Phone = "", string Email = "", bool IsActive = true, bool IsDefaultInbound = false, bool IsDefaultOutbound = false, bool AllowNegativeStock = false, bool RequiresLocation = false, string Description = "");
public sealed record WarehouseLocationEdit(string Id, string WarehouseId, string Code, string Name, string LocationType = "General", string? ParentLocationId = null, string Aisle = "", string Rack = "", string Shelf = "", string Bin = "", string? Barcode = null, decimal? Capacity = null, bool IsActive = true, bool IsDefaultInbound = false, bool IsDefaultOutbound = false, string Description = "");

public sealed class LocalWarehouseService(StoreDatabase database)
{
    public DataTable Search(string companyId, string? branchId = null, string? warehouseType = null, bool? active = null)
    {
        return database.Query("""
            SELECT w.id AS Id,w.code AS DepoKodu,w.name AS DepoAdi,c.name AS Firma,b.name AS Sube,w.warehouse_type AS DepoTipi,
                   w.address AS Adres,w.is_default_inbound AS VarsayilanGiris,w.is_default_outbound AS VarsayilanCikis,
                   w.requires_location AS LokasyonZorunlu,w.allow_negative_stock AS NegatifStok,w.is_active AS Aktif,
                   COUNT(DISTINCT ib.product_id) AS UrunSayisi,COALESCE(SUM(ib.quantity_on_hand),0) AS ToplamStok,w.updated_at AS SonGuncelleme
            FROM warehouses w JOIN companies c ON c.id=w.company_id JOIN branches b ON b.id=w.branch_id
            LEFT JOIN inventory_balances ib ON ib.warehouse_id=w.id
            WHERE w.company_id=$company AND ($branch='' OR w.branch_id=$branch) AND ($type='' OR w.warehouse_type=$type) AND ($active IS NULL OR w.is_active=$active)
            GROUP BY w.id ORDER BY w.code
            """, ("$company", companyId), ("$branch", branchId ?? ""), ("$type", warehouseType ?? ""), ("$active", active.HasValue ? active.Value ? 1 : 0 : DBNull.Value));
    }

    public DataTable Locations(string warehouseId, bool? active = null)
        => database.Query("SELECT l.id AS Id,l.code AS LokasyonKodu,l.name AS LokasyonAdi,l.location_type AS LokasyonTipi,l.aisle AS Koridor,l.rack AS Raf,l.shelf AS Bolme,l.bin AS Goz,l.barcode AS Barkod,l.capacity AS Kapasite,l.is_default_inbound AS VarsayilanGiris,l.is_default_outbound AS VarsayilanCikis,l.is_active AS Aktif,COALESCE(SUM(ib.quantity_on_hand),0) AS MevcutStok FROM warehouse_locations l LEFT JOIN warehouse_location_balances ib ON ib.location_id=l.id WHERE l.warehouse_id=$warehouse AND ($active IS NULL OR l.is_active=$active) GROUP BY l.id ORDER BY l.code", ("$warehouse", warehouseId), ("$active", active.HasValue ? active.Value ? 1 : 0 : DBNull.Value));

    public void Save(WarehouseEdit edit, string userId)
    {
        if (string.IsNullOrWhiteSpace(edit.CompanyId) || string.IsNullOrWhiteSpace(edit.BranchId) || string.IsNullOrWhiteSpace(edit.Code) || string.IsNullOrWhiteSpace(edit.Name)) throw new ArgumentException("Firma, şube, depo kodu ve depo adı zorunludur.");
        using var c = database.OpenConnection(); using var tx = c.BeginTransaction(); var id = string.IsNullOrWhiteSpace(edit.Id) ? Guid.NewGuid().ToString() : edit.Id; var now = DateTime.UtcNow.ToString("O");
        using (var validate = c.CreateCommand()) { validate.Transaction = tx; validate.CommandText = "SELECT COUNT(*) FROM branches WHERE id=$branch AND company_id=$company AND is_active=1"; Add(validate,"$branch",edit.BranchId); Add(validate,"$company",edit.CompanyId); if(Convert.ToInt32(validate.ExecuteScalar()) != 1) throw new ArgumentException("Şube seçilen firmaya ait değil veya pasif."); }
        if (edit.IsDefaultInbound) ClearDefault(c, tx, edit.CompanyId, edit.BranchId, "is_default_inbound"); if (edit.IsDefaultOutbound) ClearDefault(c, tx, edit.CompanyId, edit.BranchId, "is_default_outbound");
        using var cmd = c.CreateCommand(); cmd.Transaction = tx; cmd.CommandText = "INSERT INTO warehouses(id,company_id,branch_id,code,name,warehouse_type,address,responsible_user_id,phone,email,is_active,is_default_inbound,is_default_outbound,allow_negative_stock,requires_location,description,created_at,updated_at,created_by,updated_by) VALUES($id,$company,$branch,$code,$name,$type,$address,$responsible,$phone,$email,$active,$inbound,$outbound,$negative,$location,$description,$now,$now,$user,$user) ON CONFLICT(id) DO UPDATE SET company_id=$company,branch_id=$branch,code=$code,name=$name,warehouse_type=$type,address=$address,responsible_user_id=$responsible,phone=$phone,email=$email,is_active=$active,is_default_inbound=$inbound,is_default_outbound=$outbound,allow_negative_stock=$negative,requires_location=$location,description=$description,updated_at=$now,updated_by=$user"; Add(cmd,"$id",id); Add(cmd,"$company",edit.CompanyId); Add(cmd,"$branch",edit.BranchId); Add(cmd,"$code",edit.Code.Trim().ToUpperInvariant()); Add(cmd,"$name",edit.Name.Trim()); Add(cmd,"$type",edit.WarehouseType); Add(cmd,"$address",edit.Address); Add(cmd,"$responsible",(object?)edit.ResponsibleUserId??DBNull.Value); Add(cmd,"$phone",edit.Phone); Add(cmd,"$email",edit.Email); Add(cmd,"$active",edit.IsActive ? 1 : 0); Add(cmd,"$inbound",edit.IsDefaultInbound ? 1 : 0); Add(cmd,"$outbound",edit.IsDefaultOutbound ? 1 : 0); Add(cmd,"$negative",edit.AllowNegativeStock ? 1 : 0); Add(cmd,"$location",edit.RequiresLocation ? 1 : 0); Add(cmd,"$description",edit.Description); Add(cmd,"$now",now); Add(cmd,"$user",userId); cmd.ExecuteNonQuery(); Audit(c,tx,edit.CompanyId,id,userId,string.IsNullOrWhiteSpace(edit.Id)?"WarehouseCreated":"WarehouseUpdated",$"code={edit.Code};name={edit.Name}"); tx.Commit();
    }

    public void SaveLocation(WarehouseLocationEdit edit, string userId)
    {
        if (string.IsNullOrWhiteSpace(edit.WarehouseId) || string.IsNullOrWhiteSpace(edit.Code) || string.IsNullOrWhiteSpace(edit.Name)) throw new ArgumentException("Depo, lokasyon kodu ve lokasyon adı zorunludur."); if (edit.Capacity < 0) throw new ArgumentException("Lokasyon kapasitesi negatif olamaz."); if (edit.ParentLocationId == edit.Id && !string.IsNullOrWhiteSpace(edit.Id)) throw new ArgumentException("Lokasyon kendisini üst lokasyon olarak seçemez.");
        using var c = database.OpenConnection(); using var tx = c.BeginTransaction(); var id = string.IsNullOrWhiteSpace(edit.Id) ? Guid.NewGuid().ToString() : edit.Id; var now = DateTime.UtcNow.ToString("O"); if (edit.IsDefaultInbound) ClearLocationDefault(c,tx,edit.WarehouseId,"is_default_inbound"); if(edit.IsDefaultOutbound) ClearLocationDefault(c,tx,edit.WarehouseId,"is_default_outbound");
        using var cmd=c.CreateCommand(); cmd.Transaction=tx; cmd.CommandText="INSERT INTO warehouse_locations(id,warehouse_id,code,name,location_type,parent_location_id,aisle,rack,shelf,bin,barcode,capacity,is_active,is_default_inbound,is_default_outbound,description,created_at,updated_at) VALUES($id,$warehouse,$code,$name,$type,$parent,$aisle,$rack,$shelf,$bin,$barcode,$capacity,$active,$inbound,$outbound,$description,$now,$now) ON CONFLICT(id) DO UPDATE SET warehouse_id=$warehouse,code=$code,name=$name,location_type=$type,parent_location_id=$parent,aisle=$aisle,rack=$rack,shelf=$shelf,bin=$bin,barcode=$barcode,capacity=$capacity,is_active=$active,is_default_inbound=$inbound,is_default_outbound=$outbound,description=$description,updated_at=$now"; Add(cmd,"$id",id); Add(cmd,"$warehouse",edit.WarehouseId); Add(cmd,"$code",edit.Code.Trim().ToUpperInvariant()); Add(cmd,"$name",edit.Name.Trim()); Add(cmd,"$type",edit.LocationType); Add(cmd,"$parent",(object?)edit.ParentLocationId??DBNull.Value); Add(cmd,"$aisle",edit.Aisle); Add(cmd,"$rack",edit.Rack); Add(cmd,"$shelf",edit.Shelf); Add(cmd,"$bin",edit.Bin); Add(cmd,"$barcode",(object?)edit.Barcode??DBNull.Value); Add(cmd,"$capacity",(object?)edit.Capacity??DBNull.Value); Add(cmd,"$active",edit.IsActive?1:0); Add(cmd,"$inbound",edit.IsDefaultInbound?1:0); Add(cmd,"$outbound",edit.IsDefaultOutbound?1:0); Add(cmd,"$description",edit.Description); Add(cmd,"$now",now); cmd.ExecuteNonQuery(); var company=Scalar(c,tx,"SELECT company_id FROM warehouses WHERE id=$warehouse",("$warehouse",edit.WarehouseId))?.ToString()??""; Audit(c,tx,company,id,userId,string.IsNullOrWhiteSpace(edit.Id)?"WarehouseLocationCreated":"WarehouseLocationUpdated",$"code={edit.Code};name={edit.Name}"); tx.Commit();
    }

    private static void ClearDefault(SqliteConnection c, SqliteTransaction tx, string company, string branch, string column) { using var cmd=c.CreateCommand(); cmd.Transaction=tx; cmd.CommandText=$"UPDATE warehouses SET {column}=0,updated_at=$now WHERE company_id=$company AND branch_id=$branch"; Add(cmd,"$company",company); Add(cmd,"$branch",branch); Add(cmd,"$now",DateTime.UtcNow.ToString("O")); cmd.ExecuteNonQuery(); }
    private static void ClearLocationDefault(SqliteConnection c, SqliteTransaction tx, string warehouse, string column) { using var cmd=c.CreateCommand(); cmd.Transaction=tx; cmd.CommandText=$"UPDATE warehouse_locations SET {column}=0,updated_at=$now WHERE warehouse_id=$warehouse"; Add(cmd,"$warehouse",warehouse); Add(cmd,"$now",DateTime.UtcNow.ToString("O")); cmd.ExecuteNonQuery(); }
    private static object? Scalar(SqliteConnection c, SqliteTransaction tx, string sql, params (string Name,object Value)[] values) { using var cmd=c.CreateCommand(); cmd.Transaction=tx; cmd.CommandText=sql; foreach(var value in values) Add(cmd,value.Name,value.Value); return cmd.ExecuteScalar(); }
    private static void Audit(SqliteConnection c, SqliteTransaction tx,string company,string entity,string user,string action,string values){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="INSERT INTO audit_logs(id,user_id,company_id,entity_type,entity_id,action,new_values,created_at) VALUES($id,$user,$company,'Warehouse',$entity,$action,$values,$now)";Add(cmd,"$id",Guid.NewGuid().ToString());Add(cmd,"$user",user);Add(cmd,"$company",company);Add(cmd,"$entity",entity);Add(cmd,"$action",action);Add(cmd,"$values",values);Add(cmd,"$now",DateTime.UtcNow.ToString("O"));cmd.ExecuteNonQuery();}
    private static void Add(SqliteCommand c,string name,object value)=>c.Parameters.AddWithValue(name,value);
}
