using Microsoft.EntityFrameworkCore;
using R3.Contracts;
using R3.Domain;

namespace R3.Infrastructure;

public sealed class OrganizationRuleException(string code, string message) : Exception(message) { public string Code { get; } = code; }

public sealed class OrganizationService(R3DbContext db)
{
    private static string Normalize(string code) => code.Trim().ToUpperInvariant();
    public async Task<PagedResult<CompanyListItemDto>> SearchCompaniesAsync(PagedRequest request, bool? active, CancellationToken ct)
    { var q = db.Companies.AsNoTracking().AsQueryable(); if (active.HasValue) q = q.Where(x => x.IsActive == active); if (!string.IsNullOrWhiteSpace(request.Search)) { var s = request.Search.Trim(); q = q.Where(x => x.Code.Contains(s) || x.Name.Contains(s) || x.TaxNumber.Contains(s)); } var total = await q.CountAsync(ct); var items = await q.OrderBy(x => x.Code).Skip((request.SafePage - 1) * request.SafePageSize).Take(request.SafePageSize).Select(x => new CompanyListItemDto(x.Id, x.Code, x.Name, x.LegalName, x.TaxOffice, x.TaxNumber, x.Phone, x.Email, x.IsActive)).ToListAsync(ct); return new(items, request.SafePage, request.SafePageSize, total); }
    public Task<CompanyDetailDto?> GetCompanyAsync(Guid id, CancellationToken ct) => db.Companies.AsNoTracking().Where(x => x.Id == id).Select(x => new CompanyDetailDto(x.Id, x.Code, x.Name, x.LegalName, x.TaxOffice, x.TaxNumber, x.Phone, x.Email, x.Address, x.IsActive, x.CreatedAt, x.UpdatedAt)).SingleOrDefaultAsync(ct);
    public async Task<CompanyDetailDto> CreateCompanyAsync(CreateCompanyRequest r, CancellationToken ct) { var code = Normalize(r.Code); if (await db.Companies.AnyAsync(x => x.NormalizedCode == code, ct)) throw new OrganizationRuleException("company.code_duplicate", "Bu firma kodu zaten kullanılıyor."); var e = new OrganizationCompany { Code = r.Code.Trim(), NormalizedCode = code, Name = r.Name.Trim(), LegalName = r.LegalName.Trim(), TaxOffice = r.TaxOffice.Trim(), TaxNumber = r.TaxNumber.Trim(), Phone = r.Phone.Trim(), Email = r.Email.Trim(), Address = r.Address.Trim() }; db.Companies.Add(e); await db.SaveChangesAsync(ct); await AddAudit(e.Id, "Company", "CREATE", null, e.Name, ct); return (await GetCompanyAsync(e.Id, ct))!; }
    public async Task<CompanyDetailDto> UpdateCompanyAsync(Guid id, UpdateCompanyRequest r, CancellationToken ct) { var e = await db.Companies.SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new OrganizationRuleException("company.not_found", "Firma bulunamadı."); var code = Normalize(r.Code); if (await db.Companies.AnyAsync(x => x.Id != id && x.NormalizedCode == code, ct)) throw new OrganizationRuleException("company.code_duplicate", "Bu firma kodu zaten kullanılıyor."); e.Code = r.Code.Trim(); e.NormalizedCode = code; e.Name = r.Name.Trim(); e.LegalName = r.LegalName.Trim(); e.TaxOffice = r.TaxOffice.Trim(); e.TaxNumber = r.TaxNumber.Trim(); e.Phone = r.Phone.Trim(); e.Email = r.Email.Trim(); e.Address = r.Address.Trim(); e.IsActive = r.IsActive; e.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(ct); await AddAudit(e.Id, "Company", "UPDATE", null, e.Name, ct); return (await GetCompanyAsync(id, ct))!; }
    public Task SetCompanyActiveAsync(Guid id, bool active, CancellationToken ct) => SetActive(db.Companies, id, active, "Company", ct);
    public async Task<PagedResult<BranchListItemDto>> SearchBranchesAsync(PagedRequest request, Guid? companyId, bool? active, CancellationToken ct) { var q = db.Branches.AsNoTracking().Include(x => x.Company).AsQueryable(); if (companyId.HasValue) q = q.Where(x => x.CompanyId == companyId); if (active.HasValue) q = q.Where(x => x.IsActive == active); if (!string.IsNullOrWhiteSpace(request.Search)) { var s = request.Search.Trim(); q = q.Where(x => x.Code.Contains(s) || x.Name.Contains(s)); } var total = await q.CountAsync(ct); var items = await q.OrderBy(x => x.Code).Skip((request.SafePage - 1) * request.SafePageSize).Take(request.SafePageSize).Select(x => new BranchListItemDto(x.Id, x.CompanyId, x.Company!.Name, x.Code, x.Name, x.IsActive)).ToListAsync(ct); return new(items, request.SafePage, request.SafePageSize, total); }
    public Task<BranchDetailDto?> GetBranchAsync(Guid id, CancellationToken ct) => db.Branches.AsNoTracking().Where(x => x.Id == id).Select(x => new BranchDetailDto(x.Id, x.CompanyId, x.Code, x.Name, x.IsActive, x.CreatedAt, x.UpdatedAt)).SingleOrDefaultAsync(ct);
    public async Task<BranchDetailDto> CreateBranchAsync(CreateBranchRequest r, CancellationToken ct) { var company = await db.Companies.SingleOrDefaultAsync(x => x.Id == r.CompanyId, ct) ?? throw new OrganizationRuleException("branch.company_not_found", "Firma bulunamadı."); if (!company.IsActive) throw new OrganizationRuleException("branch.company_inactive", "Pasif firmaya şube açılamaz."); var code = Normalize(r.Code); if (await db.Branches.AnyAsync(x => x.CompanyId == r.CompanyId && x.NormalizedCode == code, ct)) throw new OrganizationRuleException("branch.code_duplicate", "Bu şube kodu firma içinde zaten kullanılıyor."); var e = new Branch { CompanyId = r.CompanyId, Code = r.Code.Trim(), NormalizedCode = code, Name = r.Name.Trim() }; db.Branches.Add(e); await db.SaveChangesAsync(ct); await AddAudit(e.Id, "Branch", "CREATE", null, e.Name, ct); return (await GetBranchAsync(e.Id, ct))!; }
    public async Task<BranchDetailDto> UpdateBranchAsync(Guid id, UpdateBranchRequest r, CancellationToken ct) { var e = await db.Branches.SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new OrganizationRuleException("branch.not_found", "Şube bulunamadı."); var company = await db.Companies.SingleOrDefaultAsync(x => x.Id == r.CompanyId, ct) ?? throw new OrganizationRuleException("branch.company_not_found", "Firma bulunamadı."); if (!company.IsActive) throw new OrganizationRuleException("branch.company_inactive", "Pasif firmaya şube bağlanamaz."); var code = Normalize(r.Code); if (await db.Branches.AnyAsync(x => x.Id != id && x.CompanyId == r.CompanyId && x.NormalizedCode == code, ct)) throw new OrganizationRuleException("branch.code_duplicate", "Bu şube kodu firma içinde zaten kullanılıyor."); e.CompanyId = r.CompanyId; e.Code = r.Code.Trim(); e.NormalizedCode = code; e.Name = r.Name.Trim(); e.IsActive = r.IsActive; e.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(ct); await AddAudit(e.Id, "Branch", "UPDATE", null, e.Name, ct); return (await GetBranchAsync(id, ct))!; }
    public Task SetBranchActiveAsync(Guid id, bool active, CancellationToken ct) => SetActive(db.Branches, id, active, "Branch", ct);
    public async Task<PagedResult<WarehouseListItemDto>> SearchWarehousesAsync(PagedRequest request, Guid? companyId, Guid? branchId, bool? active, CancellationToken ct) { var q = db.Warehouses.AsNoTracking().Include(x => x.Company).Include(x => x.Branch).AsQueryable(); if (companyId.HasValue) q = q.Where(x => x.CompanyId == companyId); if (branchId.HasValue) q = q.Where(x => x.BranchId == branchId); if (active.HasValue) q = q.Where(x => x.IsActive == active); if (!string.IsNullOrWhiteSpace(request.Search)) { var s = request.Search.Trim(); q = q.Where(x => x.Code.Contains(s) || x.Name.Contains(s)); } var total = await q.CountAsync(ct); var items = await q.OrderBy(x => x.Code).Skip((request.SafePage - 1) * request.SafePageSize).Take(request.SafePageSize).Select(x => new WarehouseListItemDto(x.Id, x.CompanyId, x.Company!.Name, x.BranchId, x.Branch!.Name, x.Code, x.Name, x.WarehouseType, x.IsActive)).ToListAsync(ct); return new(items, request.SafePage, request.SafePageSize, total); }
    public Task<WarehouseDetailDto?> GetWarehouseAsync(Guid id, CancellationToken ct) => db.Warehouses.AsNoTracking().Where(x => x.Id == id).Select(x => new WarehouseDetailDto(x.Id, x.CompanyId, x.BranchId, x.Code, x.Name, x.WarehouseType, x.IsActive, x.CreatedAt, x.UpdatedAt)).SingleOrDefaultAsync(ct);
    public async Task<WarehouseDetailDto> CreateWarehouseAsync(CreateWarehouseRequest r, CancellationToken ct) { var company = await db.Companies.SingleOrDefaultAsync(x => x.Id == r.CompanyId, ct) ?? throw new OrganizationRuleException("warehouse.company_not_found", "Firma bulunamadı."); var branch = await db.Branches.SingleOrDefaultAsync(x => x.Id == r.BranchId, ct) ?? throw new OrganizationRuleException("warehouse.branch_not_found", "Şube bulunamadı."); if (!company.IsActive) throw new OrganizationRuleException("warehouse.company_inactive", "Pasif firmaya depo açılamaz."); if (!branch.IsActive) throw new OrganizationRuleException("warehouse.branch_inactive", "Pasif şubeye depo açılamaz."); if (branch.CompanyId != r.CompanyId) throw new OrganizationRuleException("warehouse.branch_company_mismatch", "Şube seçilen firmaya ait değil."); var code = Normalize(r.Code); if (await db.Warehouses.AnyAsync(x => x.CompanyId == r.CompanyId && x.NormalizedCode == code, ct)) throw new OrganizationRuleException("warehouse.code_duplicate", "Bu depo kodu firma içinde zaten kullanılıyor."); var e = new Warehouse { CompanyId = r.CompanyId, BranchId = r.BranchId, Code = r.Code.Trim(), NormalizedCode = code, Name = r.Name.Trim(), WarehouseType = r.WarehouseType.Trim() }; db.Warehouses.Add(e); await db.SaveChangesAsync(ct); await AddAudit(e.Id, "Warehouse", "CREATE", null, e.Name, ct); return (await GetWarehouseAsync(e.Id, ct))!; }
    public async Task<WarehouseDetailDto> UpdateWarehouseAsync(Guid id, UpdateWarehouseRequest r, CancellationToken ct) { var e = await db.Warehouses.SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new OrganizationRuleException("warehouse.not_found", "Depo bulunamadı."); var company = await db.Companies.SingleOrDefaultAsync(x => x.Id == r.CompanyId, ct) ?? throw new OrganizationRuleException("warehouse.company_not_found", "Firma bulunamadı."); var branch = await db.Branches.SingleOrDefaultAsync(x => x.Id == r.BranchId, ct) ?? throw new OrganizationRuleException("warehouse.branch_not_found", "Şube bulunamadı."); if (!company.IsActive || !branch.IsActive) throw new OrganizationRuleException("warehouse.branch_inactive", "Aktif firma ve şube seçilmelidir."); if (branch.CompanyId != r.CompanyId) throw new OrganizationRuleException("warehouse.branch_company_mismatch", "Şube seçilen firmaya ait değil."); var code = Normalize(r.Code); if (await db.Warehouses.AnyAsync(x => x.Id != id && x.CompanyId == r.CompanyId && x.NormalizedCode == code, ct)) throw new OrganizationRuleException("warehouse.code_duplicate", "Bu depo kodu firma içinde zaten kullanılıyor."); e.CompanyId = r.CompanyId; e.BranchId = r.BranchId; e.Code = r.Code.Trim(); e.NormalizedCode = code; e.Name = r.Name.Trim(); e.WarehouseType = r.WarehouseType.Trim(); e.IsActive = r.IsActive; e.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(ct); await AddAudit(e.Id, "Warehouse", "UPDATE", null, e.Name, ct); return (await GetWarehouseAsync(id, ct))!; }
    public Task SetWarehouseActiveAsync(Guid id, bool active, CancellationToken ct) => SetActive(db.Warehouses, id, active, "Warehouse", ct);
    public Task<List<LookupItemDto>> CompanyLookupAsync(CancellationToken ct) => db.Companies.AsNoTracking().Where(x => x.IsActive).OrderBy(x => x.Code).Select(x => new LookupItemDto(x.Id, x.Code, x.Name)).ToListAsync(ct);
    public Task<List<LookupItemDto>> BranchLookupAsync(Guid companyId, CancellationToken ct) => db.Branches.AsNoTracking().Where(x => x.CompanyId == companyId && x.IsActive).OrderBy(x => x.Code).Select(x => new LookupItemDto(x.Id, x.Code, x.Name)).ToListAsync(ct);
    private async Task SetActive<TEntity>(DbSet<TEntity> set, Guid id, bool active, string type, CancellationToken ct) where TEntity : AuditableEntity { var e = await set.SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new OrganizationRuleException(type.ToLowerInvariant() + ".not_found", "Kayıt bulunamadı."); var property = typeof(TEntity).GetProperty("IsActive") ?? throw new InvalidOperationException(); property.SetValue(e, active); e.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(ct); await AddAudit(e.Id, type, active ? "ACTIVATE" : "DEACTIVATE", null, active.ToString(), ct); }
    private async Task AddAudit(Guid id, string type, string action, string? oldValue, string? newValue, CancellationToken ct) { db.AuditLogs.Add(new AuditLog { EntityId = id, EntityType = type, Action = action, OldValues = oldValue, NewValues = newValue }); await db.SaveChangesAsync(ct); }
}
